In [98]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (StandardScaler, OneHotEncoder, OrdinalEncoder)
pd.set_option('display.max_columns', 1000)

In [99]:
df=pd.read_csv("/home/salah-mohammed/Data_Science/ds_jobs_project/data/cleaned_dfs/updated_df.csv")
df.head()

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Country,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary,avg_salary,Skills,Web development,ERP systems,Supply chain,Research,Pro/ENGINEER,SAS,ServiceNow,Biostatistics,Database management,MRP,.NET Core,Content development,NoSQL,Machine learning,Sensors,Web analytics,Recruiting,IT,CAD,Oracle,SaaS,Microsoft Powerpoint,Virtualization,Yardi,Databases,Microsoft Windows Server,Logistics,Root cause analysis,Authentication,Scripting,Sales,Data entry,Filing,SharePoint,Clinical laboratory experience,Multilingual,Tooling,HIPAA,Software deployment,DoD experience,Statistical software,Ansible,Program management,Social listening,Unreal Engine,Waterfall,FPGA,Robotics,Organizational skills,Cloud computing,Taxonomy,Laboratory information management systems,Computer skills,Conflict management,Vendor management,Usability,FEA,Help desk,SSO,Algorithm design,Customer retention,Management,Data science,Redshift,Microsoft Word,SOX,Google Analytics,Financial modeling,Operating systems,Scientific research,Natural language processing,Process improvement,Kubernetes,Business analysis,Computer networking,Internet of Things,Construction,Optics,Relationship management,Figma,Scalability,Google Cloud Platform,Presentation skills,S3,Test-driven development,Data analysis skills,Biotechnology,Cloud infrastructure,Application development,Information security,XML,Cassandra,Ontology,GitHub,Signal processing,SSRS,IIS,Talent acquisition,Terraform,French,Microsoft SQL Server,Mandarin,MATLAB,Project management software,Distributed systems,Administrative experience,WAN,C,R,VoIP,Big data,Requirements gathering,Bootstrap,Fanuc,System design,Investment,Data centre experience,D3.js,Systems engineering,Program design,Agile,A/B testing,Statistical analysis,Microsoft PowerPoint,Embedded software,GAMP,Git,Marketing mix modeling,FedRAMP,Wealth management,AI,Telecommunication,Statistics,Configuration management,Disaster recovery,Managed care,SAP,Financial planning,Quantitative analysis,Computer operation,Performance tuning,SolidWorks,TCP,Mechanical engineering,SDKs,Pricing,Load balancing,Spark,Web accessibility,English,Warehouse management system,Cloud development,Public health,FISMA,Salesforce Marketing Cloud,React,Accounting software,UI,T-SQL,Proposal writing,New Relic,Controlling experience,Cucumber (software testing tool),Trello,Qualitative research,Cost management,Hadoop,Forecasting,Experimental design,Accounts payable,Python,Revenue cycle management,Node.js,Analytics,EDI,Kanban,Geometry,TensorFlow,Research & development,Data warehouse,Metadata,Image processing,Change management,Project coordination,Performance management,Banking,Salt,Microsoft Office,Bilingual,Data collection,Moving,Spanish,CSS,User acceptance testing,Computer vision,Quality assurance,E-commerce,Maths,Public speaking,Contract management,Data analytics,Requirements analysis,Rust (programming language),Barista experience,Clinical development,Product development,Docker,Salesforce,Schematics,NetSuite,Software architecture,Military,Leadership,Jira,Design patterns,Data visualization,Visual Basic,Data mining,Deep learning,Communication skills,Quality control,JavaScript,MongoDB,Data modeling,Operations research,Epic,Project leadership,Alteryx,Team management,Operations management,Customer service,Software troubleshooting,Internet of things,Terrafrom,Clinical research,Software testing,Business requirements,Medical imaging,Adobe Photoshop,Japanese,Marketing,C#,Data structures,Linux,Microservices,Market analysis,DB2,Hospitality,Regression analysis,Wireframing,Enterprise software,APIs,Writing skills,Russian,Java,Tableau,Market research,Incident management,Microsoft Excel,Microsoft Access,Continuous improvement,Graph databases,Electrical engineering,Test automation,.NET,Selenium,QlikView,Revit,5G,Financial services,Confluence,AWS,JSON,Azure,Project management,Data management,Systems design,Computer literacy,HP ALM,Power BI,Google Suite,Interviewing,Django,Release management,Calculus,Test management tools,Business intelligence,Analysis skills,Windows,Visual Studio,Risk management,Computer science,SQL,SVN,TypeScript,C++,Scala,Business processes,Fraud prevention and detection,Front-end development,RBAC,PaaS,Software development,System administration,System architecture,TestNG,SASS,iOS,Semantic Web,Time management,SAP SuccessFactors,SAFe,Financial analysis,SCCM,Solution architecture,Relational databases,Crystal Reports,Mobile applications,CI/CD,Knowledge management,Mentoring,Pivot tables,PostgreSQL,Swift,Microbiology,Unity,IT service management,Microsoft Outlook,Data modelling,Product demos,Math,Quality inspection,Elasticsearch,Go,AutoCAD,OOP,Organisational skills,Database development,CRM software,Debugging,Organization design,Deployment,Fiddler,DevOps,Predictive analytics,SDLC,Apache Hive,Data visualisation,REST,Distributed control systems,seniority,Job Category,skill_num
0,Data Scientist,WINTrio,Remote,NaN,Takes research methodology and translates the ...,30d+,USA,0,0,0,Unknown,NaN,NaN,NaN,"Statistics, SAS, R, Process improvement, SQL",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,Data Scientist,5
1,"Language Data Scientist, Alexa AI",Amazon,"Seattle, WA",$136K - $184K,3+ years of machine learning/statistical model...,18d,USA,0,0,1,$,136.0,184.0,160.0,"Statistics, MATLAB, SAS, Qualitative research, R",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,AI Engineer,5
2,"Data Scientist, WWPS ProServe Data and Machine...",Amazon Web Services,"Jessup, MD",$136K - $184K,"Working closely with stakeholders, you'll asse...",30d+,USA,0,0,1,$,136.0,184.0,160.0,"CI/CD, MATLAB, SAS, Software deployment, R",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,ML engineer,6
3,"Data Scientist I, SHAKE",Amazon,"Seattle, WA",$108K - $160K,You will work on our Science team and partner ...,27d,USA,0,0,1,$,108.0,160.0,134.0,"Statistics, MATLAB, Data mining, Business int...",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,Data Scientist,5
4,Lead Data Scientist,State Farm,"Bloomington, IL",$107K - $142K,Completed master’s or other advanced degree in...,18d,USA,0,0,1,$,107.0,142.0,124.5,"SAS, Computer vision, R, AWS, Team management",0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,senior,Data Scientist,6

### EDA Functions

In [100]:
"""UNIVARIATE PLOTTING FUNCTIONS FOR EDA"""
# Add the print statements to the function
def explore_categorical(df, x, fillna = True, placeholder = 'MISSING',
                        figsize = (6,4), order = None):
  """Creates a seaborn countplot with the option to temporarily fill missing values
  Prints statements about null values, cardinality, and checks for
  constant/quasi-constant features.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Make a copy of the dataframe and fillna
  temp_df = df.copy()
  # Before filling nulls, save null value counts and percent for printing
  null_count = temp_df[x].isna().sum()
  null_perc = null_count/len(temp_df)* 100
  # fillna with placeholder
  if fillna == True:
    temp_df[x] = temp_df[x].fillna(placeholder)
  # Create figure with desired figsize
  fig, ax = plt.subplots(figsize=figsize)
  # Plotting a count plot
  sns.countplot(data=temp_df, x=x, ax=ax, order=order)
  # Rotate Tick Labels for long names
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
  # Add a title with the feature name included
  ax.set_title(f"Column: {x}", fontweight='bold')

  # Fix layout and show plot (before print statements)
  fig.tight_layout()
  plt.show()
  print("*****"*10)
  # Print null value info
  print(f"- NaN's Found: {null_count} ({round(null_perc,2)}%)")
  # Print cardinality info
  nunique = temp_df[x].nunique()
  print(f"- Unique Values: {nunique}")
  # First find value counts of feature
  val_counts = temp_df[x].value_counts(dropna=False)
  # Define the most common value
  most_common_val = val_counts.index[0]
  # Define the frequency of the most common value
  freq = val_counts.values[0]
  # Calculate the percentage of the most common value
  perc_most_common = freq / len(temp_df) * 100
  # Print the results
  print(f"- Most common value: '{most_common_val}' occurs {freq} times ({round(perc_most_common,2)}%)")
  # print message if quasi-constant or constant (most common val more than 98% of data)
  if perc_most_common > 98:
    print(f"\n- [!] Warning: '{x}' is a constant or quasi-constant feature and should be dropped.")
  else:
    print("- Not constant or quasi-constant.")
  return fig, ax


# TO DO: add the new print statements from explore_categorical
def explore_numeric(df, x, figsize=(6,5) ):
  """Creates a seaborn histplot and boxplot with a share x-axis,
  Prints statements about null values, cardinality, and checks for
  constant/quasi-constant features.
  Source:{PASTE IN FINAL LESSON LINK}
  """

  ## Save null value counts and percent for printing
  null_count = df[x].isna().sum()
  null_perc = null_count/len(df)* 100


  ## Making our figure with gridspec for subplots
  gridspec = {'height_ratios':[0.7,0.3]}
  fig, axes = plt.subplots(nrows=2, figsize=figsize,
                           sharex=True, gridspec_kw=gridspec)
  # Histogram on Top
  sns.histplot(data=df, x=x, ax=axes[0])

  # Boxplot on Bottom
  sns.boxplot(data=df, x=x, ax=axes[1])

  ## Adding a title
  axes[0].set_title(f"Column: {x}", fontweight='bold')

  ## Adjusting subplots to best fill Figure
  fig.tight_layout()

  # Ensure plot is shown before message
  plt.show()

  print("*****"*10)
  # Print null value info
  print(f"- NaN's Found: {null_count} ({round(null_perc,2)}%)")
  # Print cardinality info
  nunique = df[x].nunique()
  print(f"- Unique Values: {nunique}")


  # Get the most most common value, its count as # and as %
  most_common_val_count = df[x].value_counts(dropna=False).head(1)
  most_common_val = most_common_val_count.index[0]
  freq = most_common_val_count.values[0]
  perc_most_common = freq / len(df) * 100

  print(f"- Most common value: '{most_common_val}' occurs {freq} times ({round(perc_most_common,2)}%)")

  # print message if quasi-constant or constant (most common val more than 98% of data)
  if perc_most_common > 98:
    print(f"\n- [!] Warning: '{x}' is a constant or quasi-constant feature and should be dropped.")
  else:
    print("- Not constant or quasi-constant.")
  return fig, axes

In [101]:
"""MULTIVARIATE PLOTTING FUNCTIONS VS. NUMERIC TARGET"""

def plot_categorical_vs_target(df, x, y='rating',figsize=(6,4),
                            fillna = True, placeholder = 'MISSING',
                            order = None):
  """Plots a combination of a seaborn barplot of means combined with
  a seaborn stripplot to show the spread of the data.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Make a copy of the dataframe and fillna
  temp_df = df.copy()
  # fillna with placeholder
  if fillna == True:
    temp_df[x] = temp_df[x].fillna(placeholder)

  # or drop nulls prevent unwanted 'nan' group in stripplot
  else:
    temp_df = temp_df.dropna(subset=[x])
  # Create the figure and subplots
  fig, ax = plt.subplots(figsize=figsize)

    # Barplot
  sns.barplot(data=temp_df, x=x, y=y, ax=ax, order=order, alpha=0.6,
              linewidth=1, edgecolor='black', errorbar=None)

  # Boxplot
  sns.stripplot(data=temp_df, x=x, y=y, hue=x, ax=ax,
                order=order, hue_order=order, legend=False,
                edgecolor='white', linewidth=0.5,
                size=3,zorder=0)
  # Rotate xlabels
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')

  # Add a title
  ax.set_title(f"{x} vs. {y}", fontweight='bold')
  fig.tight_layout()
  return fig, ax


def plot_numeric_vs_target(df, x, y,
                           figsize=(6,4),
                           ):
  """Plots a seaborn regplot with Pearson's correlation (r) added
  to the title.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Calculate the correlation
  corr = df[[x,y]].corr().round(2)
  r = corr.loc[x,y]

  # Plot the data
  fig, ax = plt.subplots(figsize=figsize)
  scatter_kws={'ec':'white','alpha':0.8}
  sns.regplot(data=df, x=x, y=y, ax=ax,scatter_kws=scatter_kws)

  ## Add the title with the correlation
  ax.set_title(f"{x} vs. {y} (r = {r})", fontweight='bold')

  # Make sure the plot is shown before the print statement
  plt.show()

  return fig, ax

# + Cont'd Data Preperation phase

In [102]:
drop_cols=[ 'Job Title','Company', 'Location', 'Salary Estimate', "Job Description", 'Job Age' ,'Country','Skills','min_salary','max_salary','avg_salary','currency' ]
# drop title, company, location, job descreption, job age,salary estimate , and skills are basis str (reg model wont learn, you need nlp)
# min_salary, max_salary to avoid data leakage (since target is avg_salary)
# job age text , and even we made it int, wont be that helpful
# currency captured by country, and avg_salary is in unified currency ($)

In [103]:
# drop target nans always , dont do fillna, or even preproccessing, to avoid leakage, and to combine  fake data with real data in target
# dont train model with nan target valus
df_model=df.dropna(subset='avg_salary').copy()

In [104]:
# df_model.isna().sum()
# df_model.loc[df_model.isna().any(axis=1)]
# # rest nans are in Skills col, X so in preprocessing

In [105]:
##! split data
X=df_model.drop(columns=drop_cols)
y=df_model['avg_salary']
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2,random_state=42)
X_train.head()

,Hourly,Glassdoor_Estimate,Employer_Provided,Web development,ERP systems,Supply chain,Research,Pro/ENGINEER,SAS,ServiceNow,Biostatistics,Database management,MRP,.NET Core,Content development,NoSQL,Machine learning,Sensors,Web analytics,Recruiting,IT,CAD,Oracle,SaaS,Microsoft Powerpoint,Virtualization,Yardi,Databases,Microsoft Windows Server,Logistics,Root cause analysis,Authentication,Scripting,Sales,Data entry,Filing,SharePoint,Clinical laboratory experience,Multilingual,Tooling,HIPAA,Software deployment,DoD experience,Statistical software,Ansible,Program management,Social listening,Unreal Engine,Waterfall,FPGA,Robotics,Organizational skills,Cloud computing,Taxonomy,Laboratory information management systems,Computer skills,Conflict management,Vendor management,Usability,FEA,Help desk,SSO,Algorithm design,Customer retention,Management,Data science,Redshift,Microsoft Word,SOX,Google Analytics,Financial modeling,Operating systems,Scientific research,Natural language processing,Process improvement,Kubernetes,Business analysis,Computer networking,Internet of Things,Construction,Optics,Relationship management,Figma,Scalability,Google Cloud Platform,Presentation skills,S3,Test-driven development,Data analysis skills,Biotechnology,Cloud infrastructure,Application development,Information security,XML,Cassandra,Ontology,GitHub,Signal processing,SSRS,IIS,Talent acquisition,Terraform,French,Microsoft SQL Server,Mandarin,MATLAB,Project management software,Distributed systems,Administrative experience,WAN,C,R,VoIP,Big data,Requirements gathering,Bootstrap,Fanuc,System design,Investment,Data centre experience,D3.js,Systems engineering,Program design,Agile,A/B testing,Statistical analysis,Microsoft PowerPoint,Embedded software,GAMP,Git,Marketing mix modeling,FedRAMP,Wealth management,AI,Telecommunication,Statistics,Configuration management,Disaster recovery,Managed care,SAP,Financial planning,Quantitative analysis,Computer operation,Performance tuning,SolidWorks,TCP,Mechanical engineering,SDKs,Pricing,Load balancing,Spark,Web accessibility,English,Warehouse management system,Cloud development,Public health,FISMA,Salesforce Marketing Cloud,React,Accounting software,UI,T-SQL,Proposal writing,New Relic,Controlling experience,Cucumber (software testing tool),Trello,Qualitative research,Cost management,Hadoop,Forecasting,Experimental design,Accounts payable,Python,Revenue cycle management,Node.js,Analytics,EDI,Kanban,Geometry,TensorFlow,Research & development,Data warehouse,Metadata,Image processing,Change management,Project coordination,Performance management,Banking,Salt,Microsoft Office,Bilingual,Data collection,Moving,Spanish,CSS,User acceptance testing,Computer vision,Quality assurance,E-commerce,Maths,Public speaking,Contract management,Data analytics,Requirements analysis,Rust (programming language),Barista experience,Clinical development,Product development,Docker,Salesforce,Schematics,NetSuite,Software architecture,Military,Leadership,Jira,Design patterns,Data visualization,Visual Basic,Data mining,Deep learning,Communication skills,Quality control,JavaScript,MongoDB,Data modeling,Operations research,Epic,Project leadership,Alteryx,Team management,Operations management,Customer service,Software troubleshooting,Internet of things,Terrafrom,Clinical research,Software testing,Business requirements,Medical imaging,Adobe Photoshop,Japanese,Marketing,C#,Data structures,Linux,Microservices,Market analysis,DB2,Hospitality,Regression analysis,Wireframing,Enterprise software,APIs,Writing skills,Russian,Java,Tableau,Market research,Incident management,Microsoft Excel,Microsoft Access,Continuous improvement,Graph databases,Electrical engineering,Test automation,.NET,Selenium,QlikView,Revit,5G,Financial services,Confluence,AWS,JSON,Azure,Project management,Data management,Systems design,Computer literacy,HP ALM,Power BI,Google Suite,Interviewing,Django,Release management,Calculus,Test management tools,Business intelligence,Analysis skills,Windows,Visual Studio,Risk management,Computer science,SQL,SVN,TypeScript,C++,Scala,Business processes,Fraud prevention and detection,Front-end development,RBAC,PaaS,Software development,System administration,System architecture,TestNG,SASS,iOS,Semantic Web,Time management,SAP SuccessFactors,SAFe,Financial analysis,SCCM,Solution architecture,Relational databases,Crystal Reports,Mobile applications,CI/CD,Knowledge management,Mentoring,Pivot tables,PostgreSQL,Swift,Microbiology,Unity,IT service management,Microsoft Outlook,Data modelling,Product demos,Math,Quality inspection,Elasticsearch,Go,AutoCAD,OOP,Organisational skills,Database development,CRM software,Debugging,Organization design,Deployment,Fiddler,DevOps,Predictive analytics,SDLC,Apache Hive,Data visualisation,REST,Distributed control systems,seniority,Job Category,skill_num
49,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,Data Scientist,5
98,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,senior,AI Engineer,5
526,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,senior,ML engineer,7
372,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,AI Engineer,8
291,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mid,Data Analyst,6

In [106]:
X_train.isna().sum().sum() # good luck that there is no nans, but still we will add imputer (i just want )

np.int64(0)

## Preproccessing

In [107]:
cat_cols=X_train.select_dtypes('str').columns

impute_mode=SimpleImputer(strategy="most_frequent")
ohe=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

cat_pipe=make_pipeline(impute_mode,ohe)
cat_tuple=['Categorical',cat_pipe,cat_cols]

##! ****************************************************
num_cols=X_train.select_dtypes('number').columns

impute_median=SimpleImputer(strategy='median')
scaler=StandardScaler()

num_pipe=make_pipeline(impute_median,scaler)
num_tuple=['Numarical',num_pipe,num_cols]

In [ ]:
# remmeber until now we didnt do any fit, in modeling we will fit with the preprocessor and model at the same time
preprocessor=ColumnTransformer(transformers=[cat_tuple,num_tuple],verbose_feature_names_out=False)
preprocessor

ColumnTransformer(transformers=[['Categorical',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['seniority', 'Job Category'], dtype='str')],
                                ['Numarical',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  Stan...,
                                 Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Web development',
       'ERP systems', 'Supply chain', 'Research', 'Pro/ENGINEER', 'SAS',
       'ServiceNow',
       ...
       'Deployment', 'Fiddler', 'DevOps', 'Predictive analytics', 'SDLC',
       'Apache Hive', 'Data visualisation', 'REST',
       'Distributed control systems', 'skill_num'],
      dtype='str', length=354)]],
                  verbose_feature_names_out=False)

# Modeling

In [111]:
from sklearn.linear_model import LinearRegression
# let's start with dummy model to see the flow
dummy_lin_reg = LinearRegression()
dummy_lin_reg_pipe=make_pipeline(preprocessor,dummy_lin_reg)
dummy_lin_reg_pipe.fit(X_train,y_train)
dummy_lin_reg_pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[['Categorical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['seniority', 'Job Category'], dtype='str')],
                                                 ['Numarical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strat...
                                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Web development',
       'ERP systems', 'Supply chain', 'Research', 'Pro/ENGINEER', 'SAS',
       'ServiceNow',
       ...
       'Deployment', 'Fiddler', 'DevOps', 'Predictive analytics', 'SDLC',
       'Apache Hive', 'Data visualisation', 'REST',
       'Distributed control systems', 'skill_num'],
      dtype='str', length=354)]],
                                   verbose_feature_names_out=False)),
                ('linearregression', LinearRegression())])

In [ ]:
print(f"the intercept for dummy linear reg model is {dummy_lin_reg.intercept_}")
# 111 is the avg_salary for a default job with no skills
print(f"the coefecient for dummy linear reg model is {dummy_lin_reg.coef_}")

the intercept for dummy linear reg model is 111.8165401991065
the coefecient for dummy linear reg model is [-4.33878756e+00 -3.06376705e+00  7.40255460e+00  3.01738488e+01
 -2.82694650e+01 -2.78351623e-01 -1.00119447e+01  8.38591252e+00
  5.86569720e-01 -1.00507552e+01  1.00507552e+01  2.12982074e+00
 -1.11698105e+00  1.34188678e+00  1.79887764e-01  0.00000000e+00
 -2.11206103e+00  9.24296226e-01  1.05588455e+01 -3.46389584e-14
  2.93098879e-14  1.03064504e+01 -5.07198941e-01  1.44153145e+00
 -7.69622684e+00 -5.15143483e-14  2.88657986e-14  1.05884969e+00
 -3.39591187e+00 -3.15908346e-01 -3.73921679e+00  5.32907052e-15
  1.55054982e+00 -1.28352694e+00 -6.21724894e-15 -5.47601832e+00
  1.13458116e+00 -2.10502772e-01  2.14138069e+00 -1.77635684e-15
  5.67568346e-01  2.95004384e-02 -1.07986211e+00 -4.44089210e-15
  6.63452019e+00  6.26559660e-01  7.51280377e+00 -1.81167238e-01
  1.70226011e+00  4.34267385e+00  3.54864219e+00  3.19744231e-14
 -2.08958862e+00  5.67396420e+00 -2.88902049e-01 -3.87564849e-01
 -4.98433132e+00  3.27363820e+00 -7.61746637e-02 -3.40572631e+00
  2.66690136e+00  1.08016413e+00  4.25217655e+00 -1.65887561e+00
 -1.32823795e+00  3.50502728e+00  7.14556917e+00 -1.53845361e+00
  1.02853751e+00  9.18372759e-03 -1.09539446e+00  5.22447813e+00
  1.59872116e-14 -7.23333334e+00 -6.76993339e-02 -6.06203078e-01
 -5.57824165e+00  2.33604172e+00  1.52753532e+00  1.09438713e+00
 -4.26755750e-01 -3.66734959e+00  3.85287568e+00  1.66980037e+01
 -2.25990634e-01 -2.97735618e+00  1.15699164e+00 -8.88178420e-16
  4.89963947e-01 -1.36617943e+00 -5.07198941e-01 -3.64483360e+00
  1.61244682e+01  4.50000573e+00 -3.61876928e+00 -2.16776476e+00
  7.68418956e+00 -2.28322520e+00 -2.11611569e+00 -4.78767470e+00
 -4.26855035e-01 -4.25935103e+00 -8.00824745e-02 -1.04111574e+00
  9.46016236e-01  4.46600994e+00  6.26559660e-01  1.13458116e+00
  4.43591983e-01 -7.49208956e+00  7.81401700e+00 -9.73252087e-01
 -2.66189024e+00 -1.66061690e+00 -5.07198941e-01  6.42786688e+00
 -8.46616800e-01 -2.48689958e-14  2.39924671e+00 -2.76589476e+00
 -5.32907052e-15  5.17137798e+00 -1.22120075e+00 -7.96907154e-01
  1.99274499e-02  1.50948184e+01  3.95202125e-01 -1.18678785e-01
 -2.37835676e+00  3.50309822e+00  2.45193399e+00 -3.37420738e+00
 -1.77329308e+00  6.78007139e-01  3.85413796e+00 -1.35689816e+00
 -1.63486689e+00 -1.54421369e+00 -2.88902049e-01  3.27563552e+00
 -1.16897322e+00  4.08975577e+00 -1.21040368e+00  1.92847387e+00
  3.94226022e+00 -1.01684760e+00  1.35847574e+00  5.42049146e+00
  1.23619870e+00 -4.01544755e+00  2.34785855e-01 -1.00401857e+01
 -1.33226763e-15 -8.39955518e-01 -4.44089210e-16 -4.13368759e+00
 -3.85912413e+00  7.88258347e-15 -2.20204520e+00 -7.96907154e-01
 -3.52504767e+00 -2.10502772e-01  1.71074139e+00  3.08468670e+00
  3.27563552e+00 -2.88902049e-01 -7.13531817e+00  1.79707169e+00
 -1.54558279e+00 -5.42765471e-01 -6.20534341e-01  9.32587341e-15
 -9.91778650e-01 -2.24022684e+00 -2.66453526e-15 -8.88178420e-16
  1.99274499e-02  6.69774522e-01  2.77670861e+00  3.65287853e+00
 -3.55271368e-15  1.05023592e+01  6.66221230e-02 -7.97072209e+00
 -1.55192353e+00 -7.99360578e-15 -3.91515144e-01 -4.44089210e-16
 -2.33982945e+00  8.02842032e+00 -1.39514050e+00 -2.56810028e-01
  4.58221022e-01  2.72755245e+00  1.99274499e-02  5.13413355e+00
  1.59848194e+00  2.66453526e-15  7.75640439e+00 -7.61036930e+00
  2.58300451e-02  2.17343151e+00 -2.12344982e+00 -1.03338558e+00
 -1.06851570e+00  4.94472100e+00 -1.59427648e+00 -5.25037780e-01
 -5.15448554e+00 -5.56672904e-01 -1.77635684e-15  8.99577877e-03
  4.43574947e+00  7.93321089e+00  0.00000000e+00 -7.47156933e+00
 -2.78376175e+00 -7.17201607e+00  2.95004384e-02 -8.88178420e-16
 -1.09334653e+00  2.66453526e-15 -9.52980746e+00 -1.77740041e+00
  1.07220268e+00  3.08379358e+00 -2.60003968e+00 -2.99646256e-01
  4.53622313e+00  3.13523998e+00  4.54645688e+00  1.16112969e-01
 -3.41362055e+00 -9.88093812e-02 -3.96593710e-01  5.94993815e+00
 -2.35782395e+00  4.02451310e+00 -1.53779988e+00 -2.01754118e+00
  1.86129284e+00 -6.98046831e-01 -8.39955518e-01  2.68936998e+00
 -6.76993339e-02  1.71343461e+00 -5.96967649e-01  2.22044605e-16
 -3.41582926e-01  1.13458116e+00 -1.77635684e-15 -2.88902049e-01
 -2.89681835e+00  8.16848961e-01  4.08831232e+00  1.31761805e+00
  3.26618053e+00 -3.91515144e-01 -3.34123036e+00 -4.83917150e+00
  1.89021702e+00  7.65868662e+00 -6.89813603e+00 -1.72217572e+00
  6.66133815e-16  1.78679432e+00 -5.22226975e+00  8.01698776e-01
  4.20813706e+00 -1.10056134e+01  5.08249733e+00 -1.20312883e+00
 -1.54558279e+00 -2.31971606e+00  4.09566439e+00  7.69234753e+00
 -1.90383257e-01 -3.23634061e+00  0.00000000e+00 -1.81167238e-01
 -2.00870465e+00 -8.06897196e+00  4.81586848e+00  1.21987656e+00
 -1.71022639e+01  3.49780198e-01  1.98199803e+00 -4.70197740e-38
  0.00000000e+00 -1.63486689e+00 -4.15282379e+00 -1.07580896e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.51389150e+00
 -1.63486689e+00 -1.60317396e+00 -8.60537320e+00 -8.13025971e+00
  0.00000000e+00  3.46373127e+00  2.19942968e+00  8.67859617e+00
 -2.01305493e+00 -1.16199705e+00  2.13508659e+00  7.58987810e+00
  1.04627516e+01 -1.87242603e+00 -1.54558279e+00 -8.35878734e+00
 -4.04617318e+00  1.59758821e+00 -3.91515144e-01  2.04766724e+00
  1.97129250e+00 -1.39514050e+00  0.00000000e+00 -3.91658046e-01
  1.27905272e+00 -4.84821948e+00  5.16400866e+00  2.82812519e+00
 -2.97735618e+00  0.00000000e+00  6.85168781e+00  2.47621937e+00
  1.58098657e-01  1.90934655e+00 -1.04993647e+00  5.04616449e+00
 -1.06851570e+00  1.68019562e+00  6.16824554e-01  0.00000000e+00
 -7.61746637e-02 -1.01684760e+00  2.55000919e+00  7.27612182e-01
  8.71638852e-01 -1.94599463e-01 -2.37515946e+00  0.00000000e+00
 -1.62716236e+01 -3.15908346e-01  2.22915600e-01 -2.98839527e+00
 -2.99646256e-01  4.42463576e+00 -4.35336898e+00  4.43591983e-01
  4.93301696e-01 -2.00720317e+00  4.66492460e+00  3.27934152e+00
 -7.16381946e-01  2.09781126e+00 -1.58906124e+00 -6.77608639e-01
  1.99274499e-02  3.26030449e+00]

In [114]:
dummy_lin_reg_pipe.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[['Categorical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore',
                                                                   sparse_output=False))]),
                                    Index(['seniority', 'Job Category'], dtype='str')],
                                   ['Numarical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     Stan...,
                                    Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Web development',
          'ERP systems', 'Supply chain', 'Research', 'Pro/ENGINEER', 'SAS',
          'ServiceNow',
          ...
          'Deployment', 'Fiddler', 'DevOps', 'Predictive analytics', 'SDLC',
          'Apache Hive', 'Data visualisation', 'REST',
          'Distributed control systems', 'skill_num'],
         dtype='str', length=354)]],
                     verbose_feature_names_out=False)),
  ('linearregression', LinearRegression())],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[['Categorical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse_output=False))]),
                                  Index(['seniority', 'Job Category'], dtype='str')],
                                 ['Numarical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   Stan...,
                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Web development',
        'ERP systems', 'Supply chain', 'Research', 'Pro/ENGINEER', 'SAS',
        'ServiceNow',
        ...
        'Deployment', 'Fiddler', 'DevOps', 'Predictive analytics', 'SDLC',
        'Apache Hive', 'Data visualisation', 'REST',
        'Distributed control systems', 'skill_num'],
       dtype='str', length=354)]],
                   verbose_feature_names_out=False),
 'linearregression': LinearRegression(),
 'columntransformer__force_int_remainder_cols': 'deprecated',
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [['Categorical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
   Index(['seniority', 'Job Category'], dtype='str')],
  ['Numarical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Web development',
          'ERP systems', 'Supply chain', 'Research', 'Pro/ENGINEER', 'SAS',
          'ServiceNow',
          ...
          'Deployment', 'Fiddler', 'DevOps', 'Predictive analytics', 'SDLC',
          'Apache Hive', 'Data visualisation', 'REST',
          'Distributed control systems', 'skill_num'],
         dtype='str', length=354)]],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': False,
 'columntransformer__Categorical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 'columntransformer__Numarical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__Categorical__memory': None,
 'columntransformer__Categorical__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='ignore', sparse_output=False))],
 'columntransformer__Categorical__transform_input': None,
 'columntransformer__Categorical__verbose': False,
 'columntransformer__Categorical__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__Categorical__onehotencoder': OneHotEncoder(handle_unknown='ignore', sparse_output=False),
 'columntransformer__Categorical__simpleimputer__add_indicator': False,
 'columntransformer__Categorical__simpleimputer__copy': True,
 'columntransformer__Categorical__simpleimputer__fill_value': None,
 'columntransformer__Categorical__simpleimputer__keep_empty_features': False,
 'columntransformer__Categorical__simpleimputer__missing_values': nan,
 'columntransformer__Categorical__simpleimputer__strategy': 'most_frequent',
 'columntransformer__Categorical__onehotencoder__categories': 'auto',
 'columntransformer__Categorical__onehotencoder__drop': None,
 'columntransformer__Categorical__onehotencoder__dtype': numpy.float64,
 'columntransformer__Categorical__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__Categorical__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__Categorical__onehotencoder__max_categories': None,
 'columntransformer__Categorical__onehotencoder__min_frequency': None,
 'columntransformer__Categorical__onehotencoder__sparse_output': False,
 'columntransformer__Numarical__memory': None,
 'columntransformer__Numarical__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__Numarical__transform_input': None,
 'columntransformer__Numarical__verbose': False,
 'columntransformer__Numarical__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__Numarical__standardscaler': StandardScaler(),
 'columntransformer__Numarical__simpleimputer__add_indicator': False,
 'columntransformer__Numarical__simpleimputer__copy': True,
 'columntransformer__Numarical__simpleimputer__fill_value': None,
 'columntransformer__Numarical__simpleimputer__keep_empty_features': False,
 'columntransformer__Numarical__simpleimputer__missing_values': nan,
 'columntransformer__Numarical__simpleimputer__strategy': 'median',
 'columntransformer__Numarical__standardscaler__copy': True,
 'columntransformer__Numarical__standardscaler__with_mean': True,
 'columntransformer__Numarical__standardscaler__with_std': True,
 'linearregression__copy_X': True,
 'linearregression__fit_intercept': True,
 'linearregression__n_jobs': None,
 'linearregression__positive': False,
 'linearregression__tol': 1e-06}

In [116]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error ,root_mean_squared_error

def regression_metrics(y_true, y_pred, label='', verbose = True, output_dict=False):
  # Get metrics
  mae = mean_absolute_error(y_true, y_pred)
  mse = mean_squared_error(y_true, y_pred)
  rmse = root_mean_squared_error(y_true, y_pred)
  r_squared = r2_score(y_true, y_pred)
  if verbose == True:
    # Print Result with Label and Header
    header = "-"*60
    print(header, f"Regression Metrics: {label}", header, sep='\n')
    print(f"- MAE = {mae:,.3f}")
    print(f"- MSE = {mse:,.3f}")
    print(f"- RMSE = {rmse:,.3f}")
    print(f"- R^2 = {r_squared:,.3f}")
  if output_dict == True:
      metrics = {'Label':label, 'MAE':mae,
                 'MSE':mse, 'RMSE':rmse, 'R^2':r_squared}
      return metrics

def evaluate_regression(reg, X_train, y_train, X_test, y_test, verbose = True,
                        output_frame=False):
  # Get predictions for training data
  y_train_pred = reg.predict(X_train)

  # Call the helper function to obtain regression metrics for training data
  results_train = regression_metrics(y_train, y_train_pred, verbose = verbose,
                                     output_dict=output_frame,
                                     label='Training Data')
  print()
  # Get predictions for test data
  y_test_pred = reg.predict(X_test)
  # Call the helper function to obtain regression metrics for test data
  results_test = regression_metrics(y_test, y_test_pred, verbose = verbose,
                                  output_dict=output_frame,
                                    label='Test Data' )

  # Store results in a dataframe if ouput_frame is True
  if output_frame:
    results_df = pd.DataFrame([results_train,results_test])
    # Set the label as the index
    results_df = results_df.set_index('Label')
    # Set index.name to none to get a cleaner looking result
    results_df.index.name=None
    # Return the dataframe
    return results_df.round(3)

In [117]:
evaluate_regression(dummy_lin_reg_pipe,X_train,y_train,X_test,y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 16.787
- MSE = 844.932
- RMSE = 29.068
- R^2 = 0.780

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 47.382
- MSE = 4,604.336
- RMSE = 67.855
- R^2 = -0.424

In [119]:
from sklearn.model_selection import GridSearchCV

lin_reg_param_grid = {
    'linearregression__fit_intercept': [True, False],
    'linearregression__positive': [True, False]
}
grid_search_lin_reg=GridSearchCV(estimator= dummy_lin_reg_pipe,param_grid=lin_reg_param_grid,cv=5,scoring='neg_mean_squared_error' )
grid_search_lin_reg.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[['Categorical',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         Index(['seniority', 'Job Category'], dtype='str')],
                                                                        ['Numarical',
                                                                         Pipeline(steps=[('simple...
       'Deployment', 'Fiddler', 'DevOps', 'Predictive analytics', 'SDLC',
       'Apache Hive', 'Data visualisation', 'REST',
       'Distributed control systems', 'skill_num'],
      dtype='str', length=354)]],
                                                          verbose_feature_names_out=False)),
                                       ('linearregression',
                                        LinearRegression())]),
             param_grid={'linearregression__fit_intercept': [True, False],
                         'linearregression__positive': [True, False]},
             scoring='neg_mean_squared_error')

In [120]:
evaluate_regression(grid_search_lin_reg,X_train,y_train,X_test,y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 22.357
- MSE = 1,295.757
- RMSE = 35.997
- R^2 = 0.663

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 36.902
- MSE = 2,476.964
- RMSE = 49.769
- R^2 = 0.234