In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (StandardScaler, OneHotEncoder, OrdinalEncoder)
pd.set_option('display.max_columns', 1000)

In [2]:
df=pd.read_csv("/home/salah-mohammed/Data_Science/ds_jobs_project/data/cleaned_dfs/big_updated_df.csv")
# df=df.drop(columns=['Unnamed: 0'	,'Rating'	,'Company Name'	,'Headquarters'	,'Size'	,'Founded'	,'Type of ownership'	,'Industry'	,'Sector',	'Revenue'	,'Competitors'])
df.head()

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Unnamed: 0,Rating,Company Name,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Country,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary,avg_salary,Skills,cleaned_Job,Writing skills,SAS,SAP,Relational databases,Data analytics,Project coordination,SDLC,Mandarin,Quantitative analysis,Forecasting,Public speaking,Systems design,Tooling,Organization design,Application development,SharePoint,SolidWorks,C++,Data management,Banking,TestNG,Tableau,Authentication,SVN,Public health,Web analytics,Cassandra,Yardi,IIS,JavaScript,Predictive analytics,Natural language processing,Web accessibility,Quality assurance,Virtualization,Time management,Research & development,Conflict management,Business analysis,Computer science,Embedded software,Debugging,CI/CD,Computer vision,Moving,E-commerce,Regression analysis,Microsoft Access,Oracle,CAD,Business processes,Data mining,System design,Data collection,Salesforce Marketing Cloud,Fiddler,Ansible,D3.js,Multilingual,Pro/ENGINEER,T-SQL,Waterfall,C#,Wireframing,Ontology,Military,XML,Software troubleshooting,SSRS,Market analysis,Epic,OOP,Marketing,CRM software,WAN,Project management,SASS,Risk management,Business requirements,PaaS,HP ALM,Recruiting,Performance tuning,Python,Web development,Program management,Microbiology,Customer retention,Statistical analysis,FedRAMP,Microservices,Release management,Database management,Solution architecture,Controlling experience,Vendor management,Django,Node.js,TypeScript,Elasticsearch,Linux,Distributed systems,Schematics,Databases,Mentoring,Jira,Scala,5G,Wealth management,Help desk,REST,SOX,Spark,Warehouse management system,Google Cloud Platform,Sales,Internet of things,Filing,Logistics,IT,Systems engineering,Microsoft PowerPoint,Financial analysis,.NET,Robotics,Signal processing,QlikView,Continuous improvement,Investment,Data centre experience,Big data,AWS,DevOps,Data structures,Software architecture,Cost management,Scripting,NetSuite,Requirements gathering,Requirements analysis,Data entry,Visual Basic,Load balancing,Microsoft Word,Test automation,MATLAB,Scalability,Financial modeling,Salesforce,Apache Hive,Redshift,Google Suite,Change management,SAP SuccessFactors,Operations management,Data visualization,FISMA,TCP,Confluence,SDKs,Russian,R,Data analysis skills,Deployment,Product development,Computer skills,Salt,Windows,Organisational skills,Management,Kanban,Analysis skills,UI,Performance management,Microsoft Powerpoint,Software testing,Process improvement,English,Figma,Pivot tables,Mechanical engineering,Trello,Medical imaging,Statistical software,IT service management,Hospitality,Cloud development,SaaS,System architecture,VoIP,GAMP,Machine learning,Presentation skills,Microsoft Office,Data warehouse,Disaster recovery,Front-end development,DoD experience,RBAC,ERP systems,System administration,Analytics,Maths,Azure,A/B testing,Japanese,Market research,Clinical development,Database development,Fraud prevention and detection,Bootstrap,TensorFlow,Test-driven development,Operating systems,New Relic,Usability,Math,Software development,Statistics,MongoDB,Contract management,.NET Core,Agile,Operations research,Content development,Marketing mix modeling,Terrafrom,Experimental design,Alteryx,Calculus,ServiceNow,Fanuc,Interviewing,Unity,Pricing,Computer networking,Customer service,Graph databases,FEA,French,DB2,GitHub,Bilingual,Mobile applications,SSO,Docker,Project management software,Data modelling,Microsoft SQL Server,Organizational skills,Clinical research,Supply chain,Taxonomy,HIPAA,Spanish,Cucumber (software testing tool),Telecommunication,Internet of Things,Visual Studio,Financial planning,Crystal Reports,Clinical laboratory experience,Data science,Quality control,EDI,NoSQL,Administrative experience,Biotechnology,Managed care,Team management,Construction,Unreal Engine,Test management tools,S3,Relationship management,Knowledge management,CSS,Root cause analysis,Laboratory information management systems,Metadata,Accounts payable,AutoCAD,Biostatistics,Research,Qualitative research,SCCM,Computer operation,Social listening,Electrical engineering,Kubernetes,Optics,Semantic Web,Barista experience,User acceptance testing,Software deployment,React,C,Financial services,Microsoft Windows Server,Algorithm design,PostgreSQL,Java,Cloud computing,Image processing,Data visualisation,Leadership,Project leadership,Enterprise software,Accounting software,Git,Proposal writing,Distributed control systems,Revit,Configuration management,Revenue cycle management,Sensors,Talent acquisition,Geometry,Adobe Photoshop,Deep learning,Information security,Program design,AI,Computer literacy,Go,APIs,iOS,SQL,SAFe,Quality inspection,Microsoft Outlook,Data modeling,Scientific research,Design patterns,Cloud infrastructure,Business intelligence,Selenium,Product demos,Rust (programming language),MRP,Incident management,FPGA,Microsoft Excel,Hadoop,Swift,Communication skills,Google Analytics,JSON,Terraform,Power BI,years_exp,seniority,Job Category,skill_num
0,"Language Data Scientist, Alexa AI",Amazon,"Seattle, WA",$136K - $184K,3+ years of machine learning/statistical model...,18d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,$,136.0,184.0,160.0,"Statistics, MATLAB, SAS, Qualitative research, R",3+ years of machine learning statistical model...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.0,mid,AI Engineer,7
1,Data Scientist,Tata Consultancy Services,"Louisville, KY",$110K - $140K,"3+ years in decision analytics, data science, ...",27d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,$,110.0,140.0,125.0,"Statistics, SQL, Statistical analysis, Analys...",3+ years in decision analytics data science or...,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3.0,mid,Data Scientist,7
2,Data Scientist - TikTok Integrity and Safety (...,TikTok,"San Jose, CA",$137K - $293K,2+ years of data science experience and Bachel...,30d+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,$,137.0,293.0,215.0,"Data mining, R, English, SQL, Risk management",2+ years of data science experience and bachel...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2.0,mid,Data Scientist,8
3,Data Scientist,RLDatix,Remote,NaN,3–5+ years of experience in applied data scien...,30d+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,Unknown,NaN,NaN,NaN,"TensorFlow, Azure, Google Cloud Platform, SQL...",3 5+ years of experience in applied data scien...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.0,mid,Data Scientist,7
4,Data Scientist,NTT DATA,"London, England",NaN,"Industry experience in sectors such as retail,...",30d+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,Unknown,NaN,NaN,NaN,"TensorFlow, Power BI, Cloud infrastructure, A...",industry experience in sectors such as retail ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5.0,mid,Data Scientist,6

### EDA Functions

In [3]:
"""UNIVARIATE PLOTTING FUNCTIONS FOR EDA"""
# Add the print statements to the function
def explore_categorical(df, x, fillna = True, placeholder = 'MISSING',
                        figsize = (6,4), order = None):
  """Creates a seaborn countplot with the option to temporarily fill missing values
  Prints statements about null values, cardinality, and checks for
  constant/quasi-constant features.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Make a copy of the dataframe and fillna
  temp_df = df.copy()
  # Before filling nulls, save null value counts and percent for printing
  null_count = temp_df[x].isna().sum()
  null_perc = null_count/len(temp_df)* 100
  # fillna with placeholder
  if fillna == True:
    temp_df[x] = temp_df[x].fillna(placeholder)
  # Create figure with desired figsize
  fig, ax = plt.subplots(figsize=figsize)
  # Plotting a count plot
  sns.countplot(data=temp_df, x=x, ax=ax, order=order)
  # Rotate Tick Labels for long names
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
  # Add a title with the feature name included
  ax.set_title(f"Column: {x}", fontweight='bold')

  # Fix layout and show plot (before print statements)
  fig.tight_layout()
  plt.show()
  print("*****"*10)
  # Print null value info
  print(f"- NaN's Found: {null_count} ({round(null_perc,2)}%)")
  # Print cardinality info
  nunique = temp_df[x].nunique()
  print(f"- Unique Values: {nunique}")
  # First find value counts of feature
  val_counts = temp_df[x].value_counts(dropna=False)
  # Define the most common value
  most_common_val = val_counts.index[0]
  # Define the frequency of the most common value
  freq = val_counts.values[0]
  # Calculate the percentage of the most common value
  perc_most_common = freq / len(temp_df) * 100
  # Print the results
  print(f"- Most common value: '{most_common_val}' occurs {freq} times ({round(perc_most_common,2)}%)")
  # print message if quasi-constant or constant (most common val more than 98% of data)
  if perc_most_common > 98:
    print(f"\n- [!] Warning: '{x}' is a constant or quasi-constant feature and should be dropped.")
  else:
    print("- Not constant or quasi-constant.")
  return fig, ax


# TO DO: add the new print statements from explore_categorical
def explore_numeric(df, x, figsize=(6,5) ):
  """Creates a seaborn histplot and boxplot with a share x-axis,
  Prints statements about null values, cardinality, and checks for
  constant/quasi-constant features.
  Source:{PASTE IN FINAL LESSON LINK}
  """

  ## Save null value counts and percent for printing
  null_count = df[x].isna().sum()
  null_perc = null_count/len(df)* 100


  ## Making our figure with gridspec for subplots
  gridspec = {'height_ratios':[0.7,0.3]}
  fig, axes = plt.subplots(nrows=2, figsize=figsize,
                           sharex=True, gridspec_kw=gridspec)
  # Histogram on Top
  sns.histplot(data=df, x=x, ax=axes[0])

  # Boxplot on Bottom
  sns.boxplot(data=df, x=x, ax=axes[1])

  ## Adding a title
  axes[0].set_title(f"Column: {x}", fontweight='bold')

  ## Adjusting subplots to best fill Figure
  fig.tight_layout()

  # Ensure plot is shown before message
  plt.show()

  print("*****"*10)
  # Print null value info
  print(f"- NaN's Found: {null_count} ({round(null_perc,2)}%)")
  # Print cardinality info
  nunique = df[x].nunique()
  print(f"- Unique Values: {nunique}")


  # Get the most most common value, its count as # and as %
  most_common_val_count = df[x].value_counts(dropna=False).head(1)
  most_common_val = most_common_val_count.index[0]
  freq = most_common_val_count.values[0]
  perc_most_common = freq / len(df) * 100

  print(f"- Most common value: '{most_common_val}' occurs {freq} times ({round(perc_most_common,2)}%)")

  # print message if quasi-constant or constant (most common val more than 98% of data)
  if perc_most_common > 98:
    print(f"\n- [!] Warning: '{x}' is a constant or quasi-constant feature and should be dropped.")
  else:
    print("- Not constant or quasi-constant.")
  return fig, axes

In [4]:
"""MULTIVARIATE PLOTTING FUNCTIONS VS. NUMERIC TARGET"""

def plot_categorical_vs_target(df, x, y='rating',figsize=(6,4),
                            fillna = True, placeholder = 'MISSING',
                            order = None):
  """Plots a combination of a seaborn barplot of means combined with
  a seaborn stripplot to show the spread of the data.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Make a copy of the dataframe and fillna
  temp_df = df.copy()
  # fillna with placeholder
  if fillna == True:
    temp_df[x] = temp_df[x].fillna(placeholder)

  # or drop nulls prevent unwanted 'nan' group in stripplot
  else:
    temp_df = temp_df.dropna(subset=[x])
  # Create the figure and subplots
  fig, ax = plt.subplots(figsize=figsize)

    # Barplot
  sns.barplot(data=temp_df, x=x, y=y, ax=ax, order=order, alpha=0.6,
              linewidth=1, edgecolor='black', errorbar=None)

  # Boxplot
  sns.stripplot(data=temp_df, x=x, y=y, hue=x, ax=ax,
                order=order, hue_order=order, legend=False,
                edgecolor='white', linewidth=0.5,
                size=3,zorder=0)
  # Rotate xlabels
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')

  # Add a title
  ax.set_title(f"{x} vs. {y}", fontweight='bold')
  fig.tight_layout()
  return fig, ax


def plot_numeric_vs_target(df, x, y,
                           figsize=(6,4),
                           ):
  """Plots a seaborn regplot with Pearson's correlation (r) added
  to the title.
  Source:{PASTE IN FINAL LESSON LINK}
  """
  # Calculate the correlation
  corr = df[[x,y]].corr().round(2)
  r = corr.loc[x,y]

  # Plot the data
  fig, ax = plt.subplots(figsize=figsize)
  scatter_kws={'ec':'white','alpha':0.8}
  sns.regplot(data=df, x=x, y=y, ax=ax,scatter_kws=scatter_kws)

  ## Add the title with the correlation
  ax.set_title(f"{x} vs. {y} (r = {r})", fontweight='bold')

  # Make sure the plot is shown before the print statement
  plt.show()

  return fig, ax

# + Cont'd Data Preperation phase

In [5]:
drop_cols=[ 'Job Title','Company', 'Location', 'Salary Estimate', "Job Description", 'Job Age' ,'Country','Skills','min_salary','max_salary','avg_salary','currency' ,'Unnamed: 0'	,'Rating'	,'Company Name'	,'Headquarters'	,'Size'	,'Founded'	,'Type of ownership'	,'Industry'	,'Sector',	'Revenue'	,'Competitors','cleaned_Job']

# drop title, company, location, job descreption, job age,salary estimate , and skills are basis str (reg model wont learn, you need nlp)
# min_salary, max_salary to avoid data leakage (since target is avg_salary)
# job age text , and even we made it int, wont be that helpful
# currency captured by country, and avg_salary is in unified currency ($)

In [6]:
df.shape

(716, 381)

In [7]:
# drop target nans always , dont do fillna, or even preproccessing, to avoid leakage, and to combine  fake data with real data in target
# dont train model with nan target valus
df_model=df.dropna(subset='avg_salary').copy()

In [8]:
df_model.shape

(532, 381)

In [9]:
# df_model.isna().sum()
# df_model.loc[df_model.isna().any(axis=1)]
# # rest nans are in Skills col, X so in preprocessing

In [10]:
##! split data
X=df_model.drop(columns=drop_cols)
y=df_model['avg_salary']
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2,random_state=42)
X_train.head()

,Hourly,Glassdoor_Estimate,Employer_Provided,Writing skills,SAS,SAP,Relational databases,Data analytics,Project coordination,SDLC,Mandarin,Quantitative analysis,Forecasting,Public speaking,Systems design,Tooling,Organization design,Application development,SharePoint,SolidWorks,C++,Data management,Banking,TestNG,Tableau,Authentication,SVN,Public health,Web analytics,Cassandra,Yardi,IIS,JavaScript,Predictive analytics,Natural language processing,Web accessibility,Quality assurance,Virtualization,Time management,Research & development,Conflict management,Business analysis,Computer science,Embedded software,Debugging,CI/CD,Computer vision,Moving,E-commerce,Regression analysis,Microsoft Access,Oracle,CAD,Business processes,Data mining,System design,Data collection,Salesforce Marketing Cloud,Fiddler,Ansible,D3.js,Multilingual,Pro/ENGINEER,T-SQL,Waterfall,C#,Wireframing,Ontology,Military,XML,Software troubleshooting,SSRS,Market analysis,Epic,OOP,Marketing,CRM software,WAN,Project management,SASS,Risk management,Business requirements,PaaS,HP ALM,Recruiting,Performance tuning,Python,Web development,Program management,Microbiology,Customer retention,Statistical analysis,FedRAMP,Microservices,Release management,Database management,Solution architecture,Controlling experience,Vendor management,Django,Node.js,TypeScript,Elasticsearch,Linux,Distributed systems,Schematics,Databases,Mentoring,Jira,Scala,5G,Wealth management,Help desk,REST,SOX,Spark,Warehouse management system,Google Cloud Platform,Sales,Internet of things,Filing,Logistics,IT,Systems engineering,Microsoft PowerPoint,Financial analysis,.NET,Robotics,Signal processing,QlikView,Continuous improvement,Investment,Data centre experience,Big data,AWS,DevOps,Data structures,Software architecture,Cost management,Scripting,NetSuite,Requirements gathering,Requirements analysis,Data entry,Visual Basic,Load balancing,Microsoft Word,Test automation,MATLAB,Scalability,Financial modeling,Salesforce,Apache Hive,Redshift,Google Suite,Change management,SAP SuccessFactors,Operations management,Data visualization,FISMA,TCP,Confluence,SDKs,Russian,R,Data analysis skills,Deployment,Product development,Computer skills,Salt,Windows,Organisational skills,Management,Kanban,Analysis skills,UI,Performance management,Microsoft Powerpoint,Software testing,Process improvement,English,Figma,Pivot tables,Mechanical engineering,Trello,Medical imaging,Statistical software,IT service management,Hospitality,Cloud development,SaaS,System architecture,VoIP,GAMP,Machine learning,Presentation skills,Microsoft Office,Data warehouse,Disaster recovery,Front-end development,DoD experience,RBAC,ERP systems,System administration,Analytics,Maths,Azure,A/B testing,Japanese,Market research,Clinical development,Database development,Fraud prevention and detection,Bootstrap,TensorFlow,Test-driven development,Operating systems,New Relic,Usability,Math,Software development,Statistics,MongoDB,Contract management,.NET Core,Agile,Operations research,Content development,Marketing mix modeling,Terrafrom,Experimental design,Alteryx,Calculus,ServiceNow,Fanuc,Interviewing,Unity,Pricing,Computer networking,Customer service,Graph databases,FEA,French,DB2,GitHub,Bilingual,Mobile applications,SSO,Docker,Project management software,Data modelling,Microsoft SQL Server,Organizational skills,Clinical research,Supply chain,Taxonomy,HIPAA,Spanish,Cucumber (software testing tool),Telecommunication,Internet of Things,Visual Studio,Financial planning,Crystal Reports,Clinical laboratory experience,Data science,Quality control,EDI,NoSQL,Administrative experience,Biotechnology,Managed care,Team management,Construction,Unreal Engine,Test management tools,S3,Relationship management,Knowledge management,CSS,Root cause analysis,Laboratory information management systems,Metadata,Accounts payable,AutoCAD,Biostatistics,Research,Qualitative research,SCCM,Computer operation,Social listening,Electrical engineering,Kubernetes,Optics,Semantic Web,Barista experience,User acceptance testing,Software deployment,React,C,Financial services,Microsoft Windows Server,Algorithm design,PostgreSQL,Java,Cloud computing,Image processing,Data visualisation,Leadership,Project leadership,Enterprise software,Accounting software,Git,Proposal writing,Distributed control systems,Revit,Configuration management,Revenue cycle management,Sensors,Talent acquisition,Geometry,Adobe Photoshop,Deep learning,Information security,Program design,AI,Computer literacy,Go,APIs,iOS,SQL,SAFe,Quality inspection,Microsoft Outlook,Data modeling,Scientific research,Design patterns,Cloud infrastructure,Business intelligence,Selenium,Product demos,Rust (programming language),MRP,Incident management,FPGA,Microsoft Excel,Hadoop,Swift,Communication skills,Google Analytics,JSON,Terraform,Power BI,years_exp,seniority,Job Category,skill_num
404,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,6.0,mid,Data Scientist,8
541,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.0,mid,Data Scientist,16
602,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,7.0,mid,Data Scientist,15
424,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.0,senior,Data Scientist,19
183,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,5.0,mid,Data Scientist,21

In [11]:
X_train.isna().sum().sum() # good luck that there is no nans, but still we will add imputer (i just want )

np.int64(0)

## Preproccessing

In [12]:
cat_cols=X_train.select_dtypes('str').columns

impute_mode=SimpleImputer(strategy="most_frequent")
ohe=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

cat_pipe=make_pipeline(impute_mode,ohe)
cat_tuple=['Categorical',cat_pipe,cat_cols]

##! ****************************************************
num_cols=X_train.select_dtypes('number').columns

impute_median=SimpleImputer(strategy='median')
scaler=StandardScaler()

num_pipe=make_pipeline(impute_median,scaler)
num_tuple=['Numarical',num_pipe,num_cols]

In [13]:
# remmeber until now we didnt do any fit, in modeling we will fit with the preprocessor and model at the same time
preprocessor=ColumnTransformer(transformers=[cat_tuple,num_tuple],verbose_feature_names_out=False)
preprocessor

ColumnTransformer(transformers=[['Categorical',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['seniority', 'Job Category'], dtype='str')],
                                ['Numarical',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  Stan...ler())]),
                                 Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
       'SAS', 'SAP', 'Relational databases', 'Data analytics',
       'Project coordination', 'SDLC',
       ...
       'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
       'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
       'skill_num'],
      dtype='str', length=355)]],
                  verbose_feature_names_out=False)

In [14]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error ,root_mean_squared_error

def regression_metrics(y_true, y_pred, label='', verbose = True, output_dict=False):
  # Get metrics
  mae = mean_absolute_error(y_true, y_pred)
  mse = mean_squared_error(y_true, y_pred)
  rmse = root_mean_squared_error(y_true, y_pred)
  r_squared = r2_score(y_true, y_pred)
  if verbose == True:
    # Print Result with Label and Header
    header = "-"*60
    print(header, f"Regression Metrics: {label}", header, sep='\n')
    print(f"- MAE = {mae:,.3f}")
    print(f"- MSE = {mse:,.3f}")
    print(f"- RMSE = {rmse:,.3f}")
    print(f"- R^2 = {r_squared:,.3f}")
  if output_dict == True:
      metrics = {'Label':label, 'MAE':mae,
                 'MSE':mse, 'RMSE':rmse, 'R^2':r_squared}
      return metrics

def evaluate_regression(reg, X_train, y_train, X_test, y_test, verbose = True,
                        output_frame=False):
  # Get predictions for training data
  y_train_pred = reg.predict(X_train)

  # Call the helper function to obtain regression metrics for training data
  results_train = regression_metrics(y_train, y_train_pred, verbose = verbose,
                                     output_dict=output_frame,
                                     label='Training Data')
  print()
  # Get predictions for test data
  y_test_pred = reg.predict(X_test)
  # Call the helper function to obtain regression metrics for test data
  results_test = regression_metrics(y_test, y_test_pred, verbose = verbose,
                                  output_dict=output_frame,
                                    label='Test Data' )

  # Store results in a dataframe if ouput_frame is True
  if output_frame:
    results_df = pd.DataFrame([results_train,results_test])
    # Set the label as the index
    results_df = results_df.set_index('Label')
    # Set index.name to none to get a cleaner looking result
    results_df.index.name=None
    # Return the dataframe
    return results_df.round(3)

# Modeling

## Linear REgression Model

In [ ]:
from sklearn.linear_model import LinearRegression

dummy_lin_reg = LinearRegression()
dummy_lin_reg_pipe=make_pipeline(preprocessor,dummy_lin_reg)
dummy_lin_reg_pipe.fit(X_train,y_train)
dummy_lin_reg_pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[['Categorical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['seniority', 'Job Category'], dtype='str')],
                                                 ['Numarical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strat...
                                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
       'SAS', 'SAP', 'Relational databases', 'Data analytics',
       'Project coordination', 'SDLC',
       ...
       'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
       'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
       'skill_num'],
      dtype='str', length=355)]],
                                   verbose_feature_names_out=False)),
                ('linearregression', LinearRegression())])

In [16]:
print(f"the intercept for dummy linear reg model is {dummy_lin_reg.intercept_}")
print(f"the coefecient for dummy linear reg model is {dummy_lin_reg.coef_}")

the intercept for dummy linear reg model is 130.75845465555656
the coefecient for dummy linear reg model is [ 3.65666533e+01 -2.99217171e+01 -6.64493614e+00 -1.02812874e+01
 -2.00713757e+01 -4.21279615e+00  3.45654593e+01 -2.06152187e+00
  7.31954950e+00  8.34355681e+00 -3.88807324e+00 -4.09476655e-01
  1.46514871e+00  7.66129855e-01 -6.57111491e+00 -1.23012711e-13
 -6.86694447e+00 -6.49530267e-01  3.31166695e+00 -9.56735516e-01
  3.49093259e+00 -6.07793206e+00 -3.11297524e+00 -1.55431223e-14
  3.62217562e+00 -4.28104261e+00 -3.25073302e-13  3.37507799e-14
  2.50580896e+00 -5.17009950e+00  7.68274333e-14 -1.23585141e+01
  9.37028233e-14  6.30606678e-14 -2.19837069e+00  4.47595865e+00
 -5.24679887e+00  5.86546994e-01 -2.03954909e-13 -6.46772002e+00
 -3.14998223e+00  1.01847747e+01 -1.84519067e-13  1.82082374e+00
 -1.17215572e+01 -4.18658297e+00 -8.37108161e-14 -4.13398866e-01
  4.80099764e+00 -2.66082438e+00  3.55271368e-15 -5.28892323e+00
  2.93098879e-14 -3.70771309e+00  5.19780669e+00 -3.01980663e-14
  2.72054961e+00  9.09331354e-01  1.15708587e+00  3.24522765e-02
 -3.77949585e+00 -7.11384487e+00 -7.89115678e-01  4.62796380e+00
 -2.62028142e+00 -6.25435553e-01  1.11169792e+01 -1.30995541e+00
 -6.49530267e-01  5.86197757e-14 -1.42108547e-14 -1.15907284e-13
  1.42108547e-14 -8.97060204e-14  1.27009299e+01 -4.56830197e+00
  5.38322223e+00 -2.77068561e-01 -8.35886527e-01  1.19855415e+01
 -7.71502002e-02 -8.88178420e-15  2.03869804e+00 -7.49015842e-01
 -3.43058915e-14 -7.59447147e+00 -1.24344979e-14  8.96563274e+00
  5.17041432e+00  1.85230493e+00  1.42108547e-14 -5.41279983e+00
  1.48812817e+00 -2.66572326e+00  3.75809942e+00 -7.75905745e-01
  5.01595310e+00  5.66331418e+00  3.54595606e+00 -2.35367281e-14
 -8.62813882e+00  6.81759133e+00 -4.54727757e-01 -4.01900735e-14
 -7.49015842e-01  1.33226763e-15 -1.22171106e+01  2.37180388e+00
  7.89228236e+00 -6.44107787e+00 -4.88882391e-01 -4.61356594e+00
 -3.10862447e-14  4.68438722e+00 -5.17626736e+00  1.12989775e+01
 -2.13118920e+00  3.44169138e-14  1.28785871e-14  8.45777219e+00
  8.11529101e+00 -1.19904087e-14  1.00724728e+01  3.01980663e-14
  4.95724294e+00 -3.84732023e+00 -6.91553126e-01  8.19692373e+00
  5.68360485e+00 -5.15818541e-01 -2.91362884e+00 -2.78384015e+00
  1.89669144e+01  2.30926389e-14 -4.41149363e+00 -3.76951816e+00
  4.36569065e-01  1.98384922e+00  7.60652437e-01  2.66453526e-15
  3.51746543e+00  5.18061064e+00  4.43222200e-01  2.88759264e+00
  7.99360578e-15  4.70734562e-14 -3.93722218e+00  1.01237792e+00
  3.25567702e+00 -1.19520650e+00  2.48689958e-14 -7.27328296e+00
  8.88178420e-15 -3.66149075e+00  2.66453526e-14  4.15491475e+00
  2.95062981e-02  5.86546994e-01  4.26897190e+00 -1.83568726e+00
 -7.08710681e-01  1.59872116e-14 -4.40475685e+00  2.66453526e-15
 -1.05266527e+01  2.49387991e+00  2.22044605e-14 -2.77068561e-01
 -1.06168680e+01 -1.68753900e-14  7.99360578e-15  1.23549115e+01
  1.89514527e+00 -3.47429971e+00 -6.59142897e+00 -4.67016733e+00
  2.22044605e-14  5.00036865e+00  3.33066907e-15 -1.89706307e+00
 -1.17984869e+01 -3.21052506e+00 -5.72418490e+00  1.92381906e+00
 -2.78384015e+00  4.44089210e-15  2.53446245e+00  3.43765989e+00
  1.37667655e-14  5.94014343e+00  3.64153152e-14  6.85055363e-01
 -2.20679274e+00  5.93131172e-02 -1.06581410e-14  2.32170972e+00
  3.09119070e+00 -6.00896586e-01 -2.66453526e-14 -2.30926389e-14
  1.24344979e-14 -3.74378765e+00  2.66857831e+00 -5.45818683e-01
 -6.94357352e+00  7.14826119e+00  1.24344979e-14 -4.44089210e-15
 -2.13162821e-14 -2.22044605e-15 -1.77635684e-15 -2.36818446e-01
  1.99840144e-14 -8.65019459e+00  1.99840144e-14 -2.77068561e-01
 -7.90281833e-01 -2.56693550e+00 -1.39975690e+00 -1.95399252e-14
  1.25909754e+00 -2.77580751e+00  0.00000000e+00  9.77684992e+00
  7.10542736e-15  4.63931918e+00  6.83933568e+00  4.77145683e+00
 -4.83164420e+00  3.10638143e+00 -9.76996262e-15  3.55271368e-15
 -2.25854280e+00  2.93020934e-01 -4.44089210e-16  4.27010659e+00
  8.88178420e-16  2.33718066e+00  2.69697296e+00 -4.35760068e+00
 -4.72997898e+00  4.44089210e-16  1.81569441e+00  2.86437540e-14
 -1.65809819e+00  0.00000000e+00 -7.80587580e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.35006472e+00 -4.31502955e+00
 -6.49530267e-01  0.00000000e+00  0.00000000e+00 -4.15322860e+00
  0.00000000e+00  3.71201571e-01 -5.24195257e+00 -3.91912440e-01
 -3.29419803e+00  6.61014898e+00  0.00000000e+00 -5.07969064e+00
 -2.74530779e+00  0.00000000e+00  0.00000000e+00 -6.91553126e-01
 -2.25817799e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  6.18328598e+00  3.43910907e-01  3.71033669e+00  3.61790569e+00
  0.00000000e+00  1.99746310e+00  1.92762541e+00 -1.15718718e+00
 -7.01233492e+00  0.00000000e+00  0.00000000e+00 -2.90511620e+00
  0.00000000e+00  2.20699091e+00  1.40161470e+00 -8.30512283e-02
  0.00000000e+00  3.43050169e+00  6.60717189e-01  3.24522765e-02
 -1.95071271e+00 -1.56718445e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  1.35665481e+00  5.20468442e+00  5.84274025e-01
  1.27655342e+00  0.00000000e+00  0.00000000e+00 -7.33946123e+00
 -4.13691804e+00 -1.96260647e+00  6.91070960e-01 -5.52503787e+00
  0.00000000e+00  0.00000000e+00 -5.27243919e+00 -4.51074619e+00
  5.28003269e+00  6.82015952e+00 -1.71466203e+00  2.80555490e+00
  1.74371699e+00  8.61804395e+00 -1.15718718e+00  5.85131408e+00
  5.89145334e+00  0.00000000e+00  0.00000000e+00  1.58883280e-01
 -2.20033749e+01  5.41192936e+00 -1.95599427e+00  0.00000000e+00
  0.00000000e+00 -4.39779382e+00 -2.42761835e+00 -1.41383366e+00
  9.41013517e+00  0.00000000e+00 -2.84448340e+00  1.28259490e+00
  5.63330882e+00 -1.70284773e+00 -4.88653854e+00  0.00000000e+00
  0.00000000e+00  2.50391929e+00 -6.41849277e+00  6.28928501e-01
  2.75608160e+00  9.33170244e+00  7.69757029e-01  0.00000000e+00
  0.00000000e+00  6.85055363e-01  1.28045144e+00  0.00000000e+00
 -2.06764564e+00  1.00899685e+00  1.79054504e+01  6.60696860e+00
 -7.10921218e+00 -1.52062987e+01  4.58608292e-01  1.09287934e+01
  9.87679317e+00  5.69291361e-01]

In [17]:
evaluate_regression(dummy_lin_reg_pipe,X_train,y_train,X_test,y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 7.677
- MSE = 124.956
- RMSE = 11.178
- R^2 = 0.913

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 25.248
- MSE = 1,832.300
- RMSE = 42.805
- R^2 = -0.228

- Note that these values when we used only new jobs data (/updated_df)
---------------------------------------------------------

1. MAE:
- in training => model is off by 16.78 (~$16.8k)
- in testing => model is off by 47.3 (~$47.3k)
- Overfitting
------------------------------------------------
2. MSE:
- in training => 844
- in testing => 4,604
- model is making very big mistakes in testing data
-----------------------------------------------
3. RMSE:
- in training => 29
- in testing => 67.8
- typical prediction error ~$68k
-----------------------------------------------
4. R2:
- in training => model explains 78% of verience
- in testing => model is worse than predicting the avarage salary for each job
-----------------------------------------------
-----------------------------------------------
### ***the problem is high dimension (368), and too few rows (637)***
- i will fetch more data or better, i will handle old fetched data jobs csv, (back to data understanding and preperation.ipynb)
- i will use skill_cols to extract skills from the new jobs (since there is difference in the job descreption structre)
- new jobs: (SKills : skill1,skill2,skill3,...)
- old jobs: (skills: 3 years in skill1, professional in data cleaning, should be use power pi ,....)
-  so the best way is using the extracted skills from new jobs descreptions, and use it old jobs descreptions
---------------------------------------------------------------------------------------
- Now check the improvemnts when tried it on merged data:
--------------------------------------------------------------
1. MAE:
- in training => model is off by 20.68 (~$20.68k)
- in testing => model is off by 29.3 (~$29.3k)
- better than previous
------------------------------------------------
2. MSE:
- in training => 984.
- in testing => 1,793
- model is making very big mistakes in testing data
-----------------------------------------------
3. RMSE:
- in training => 31.37
- in testing => 42.34
- typical prediction error ~$68k
-----------------------------------------------
4. R2:
- in training => model explains 59% of verience
- in testing => now 25 
----------------------------------------------------------------
## so Grid search enhaned the explained verience in testing, and helped decreasing the overfitting, but still the model verience explaination not good

In [18]:
dummy_lin_reg_pipe.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[['Categorical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore',
                                                                   sparse_output=False))]),
                                    Index(['seniority', 'Job Category'], dtype='str')],
                                   ['Numarical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     Stan...ler())]),
                                    Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
          'SAS', 'SAP', 'Relational databases', 'Data analytics',
          'Project coordination', 'SDLC',
          ...
          'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
          'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
          'skill_num'],
         dtype='str', length=355)]],
                     verbose_feature_names_out=False)),
  ('linearregression', LinearRegression())],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[['Categorical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse_output=False))]),
                                  Index(['seniority', 'Job Category'], dtype='str')],
                                 ['Numarical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   Stan...ler())]),
                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
        'SAS', 'SAP', 'Relational databases', 'Data analytics',
        'Project coordination', 'SDLC',
        ...
        'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
        'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
        'skill_num'],
       dtype='str', length=355)]],
                   verbose_feature_names_out=False),
 'linearregression': LinearRegression(),
 'columntransformer__force_int_remainder_cols': 'deprecated',
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [['Categorical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
   Index(['seniority', 'Job Category'], dtype='str')],
  ['Numarical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
          'SAS', 'SAP', 'Relational databases', 'Data analytics',
          'Project coordination', 'SDLC',
          ...
          'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
          'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
          'skill_num'],
         dtype='str', length=355)]],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': False,
 'columntransformer__Categorical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 'columntransformer__Numarical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__Categorical__memory': None,
 'columntransformer__Categorical__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='ignore', sparse_output=False))],
 'columntransformer__Categorical__transform_input': None,
 'columntransformer__Categorical__verbose': False,
 'columntransformer__Categorical__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__Categorical__onehotencoder': OneHotEncoder(handle_unknown='ignore', sparse_output=False),
 'columntransformer__Categorical__simpleimputer__add_indicator': False,
 'columntransformer__Categorical__simpleimputer__copy': True,
 'columntransformer__Categorical__simpleimputer__fill_value': None,
 'columntransformer__Categorical__simpleimputer__keep_empty_features': False,
 'columntransformer__Categorical__simpleimputer__missing_values': nan,
 'columntransformer__Categorical__simpleimputer__strategy': 'most_frequent',
 'columntransformer__Categorical__onehotencoder__categories': 'auto',
 'columntransformer__Categorical__onehotencoder__drop': None,
 'columntransformer__Categorical__onehotencoder__dtype': numpy.float64,
 'columntransformer__Categorical__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__Categorical__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__Categorical__onehotencoder__max_categories': None,
 'columntransformer__Categorical__onehotencoder__min_frequency': None,
 'columntransformer__Categorical__onehotencoder__sparse_output': False,
 'columntransformer__Numarical__memory': None,
 'columntransformer__Numarical__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__Numarical__transform_input': None,
 'columntransformer__Numarical__verbose': False,
 'columntransformer__Numarical__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__Numarical__standardscaler': StandardScaler(),
 'columntransformer__Numarical__simpleimputer__add_indicator': False,
 'columntransformer__Numarical__simpleimputer__copy': True,
 'columntransformer__Numarical__simpleimputer__fill_value': None,
 'columntransformer__Numarical__simpleimputer__keep_empty_features': False,
 'columntransformer__Numarical__simpleimputer__missing_values': nan,
 'columntransformer__Numarical__simpleimputer__strategy': 'median',
 'columntransformer__Numarical__standardscaler__copy': True,
 'columntransformer__Numarical__standardscaler__with_mean': True,
 'columntransformer__Numarical__standardscaler__with_std': True,
 'linearregression__copy_X': True,
 'linearregression__fit_intercept': True,
 'linearregression__n_jobs': None,
 'linearregression__positive': False,
 'linearregression__tol': 1e-06}

In [19]:
from sklearn.model_selection import GridSearchCV

lin_reg_param_grid = {
    'linearregression__fit_intercept': [True, False],
    'linearregression__positive': [True, False]
}
grid_search_lin_reg=GridSearchCV(estimator= dummy_lin_reg_pipe,param_grid=lin_reg_param_grid,cv=5,scoring='neg_mean_squared_error' )
grid_search_lin_reg.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[['Categorical',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         Index(['seniority', 'Job Category'], dtype='str')],
                                                                        ['Numarical',
                                                                         Pipeline(steps=[('simple...
       'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
       'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
       'skill_num'],
      dtype='str', length=355)]],
                                                          verbose_feature_names_out=False)),
                                       ('linearregression',
                                        LinearRegression())]),
             param_grid={'linearregression__fit_intercept': [True, False],
                         'linearregression__positive': [True, False]},
             scoring='neg_mean_squared_error')

In [20]:
evaluate_regression(grid_search_lin_reg,X_train,y_train,X_test,y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 17.339
- MSE = 540.588
- RMSE = 23.251
- R^2 = 0.624

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 21.721
- MSE = 918.523
- RMSE = 30.307
- R^2 = 0.384

## Ridge

In [ ]:
from sklearn.linear_model import Ridge, Lasso
ridge=Ridge()
ridge_pipe=make_pipeline(preprocessor,ridge)
ridge_pipe.fit(X_train,y_train)

evaluate_regression(ridge_pipe,X_train=X_train,X_test=X_test,y_train=y_train,y_test=y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 7.733
- MSE = 128.245
- RMSE = 11.325
- R^2 = 0.911

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 23.015
- MSE = 1,433.753
- RMSE = 37.865
- R^2 = 0.039

In [23]:
ridge_param_grid = {'ridge__alpha': [0.1, 1, 10, 50, 100, 200, 500]}

ridge_grid = GridSearchCV(
    estimator=ridge_pipe,
    param_grid=ridge_param_grid,
    cv=5,
    scoring='neg_mean_squared_error'
)
ridge_grid.fit(X_train, y_train)
evaluate_regression(ridge_grid, X_train, y_train, X_test, y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 11.965
- MSE = 283.193
- RMSE = 16.828
- R^2 = 0.803

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 19.054
- MSE = 707.402
- RMSE = 26.597
- R^2 = 0.526

## Lasso

In [ ]:
lasso=Lasso()
lasso_pipe=make_pipeline(preprocessor,lasso)
lasso_pipe.fit(X_train,y_train)

evaluate_regression(lasso_pipe,X_train=X_train,X_test=X_test,y_train=y_train,y_test=y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 15.494
- MSE = 404.631
- RMSE = 20.115
- R^2 = 0.718

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 19.442
- MSE = 705.295
- RMSE = 26.557
- R^2 = 0.527

In [25]:
lasso_param_grid = {'lasso__alpha': [0.01, 0.1, 1, 5, 10, 50, 100]}

lasso_grid = GridSearchCV(
    estimator=lasso_pipe,
    param_grid=lasso_param_grid,
    cv=5,
    scoring='neg_mean_squared_error'
)
lasso_grid.fit(X_train, y_train)
print("Best alpha:", lasso_grid.best_params_)
print("\nLasso Tuned:")
evaluate_regression(lasso_grid, X_train, y_train, X_test, y_test)

/home/salah-mohammed/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.013e+03, tolerance: 4.807e+01
  model = cd_fast.enet_coordinate_descent(
/home/salah-mohammed/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.058e+02, tolerance: 4.594e+01
  model = cd_fast.enet_coordinate_descent(
/home/salah-mohammed/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.067e+03, tolerance: 5.237e+01
  model = cd_fast.enet_coordinate_descent(
/home/salah-mohammed/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.118e+03, tolerance: 5.026e+01
  model = cd_fast.enet_coordinate_descent(
/home/salah-mohammed/miniconda3/envs/ds/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.202e+03, tolerance: 4.747e+01
  model = cd_fast.enet_coordinate_descent(

Best alpha: {'lasso__alpha': 1}

Lasso Tuned:
------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 15.494
- MSE = 404.631
- RMSE = 20.115
- R^2 = 0.718

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 19.442
- MSE = 705.295
- RMSE = 26.557
- R^2 = 0.527

In [26]:
df_model.groupby(['seniority', 'Job Category'])['years_exp'].agg(['mean', 'median', 'count'])
# ai engineer senior: 50 year median, a7a
# also ai engineer , and data scientist juniors , are nans, also deep learning senior is nan
#  about ai engineer , and data scientist juniors at most it will be 2 years

                              mean  median  count
seniority Job Category
junior    Data Analyst    3.000000     3.0      1
mid       AI Engineer     4.000000     3.5      8
          Data Analyst    3.093750     3.0     64
          Data Scientist  4.200704     4.0    284
          Deep Learning   2.000000     2.0      1
          ML engineer     5.411765     5.0     17
senior    AI Engineer     4.666667     4.0      3
          Data Analyst    4.818182     5.0     22
          Data Scientist  4.682540     5.0    126
          ML engineer     4.333333     4.0      6

In [27]:
outlier_years=df.loc[df['years_exp']>15]
outlier_years.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Columns: 381 entries, Job Title to skill_num
dtypes: float64(7), int64(354), str(20)
memory usage: 132.0 bytes

In [28]:
# i will use industry standard- years of exp to fill nans:
seniority_years={
    'junior':2,
    'mid':4,
    'senior':7
}
df_model['years_exp'] = df_model.apply(
    lambda row: seniority_years[row['seniority']] 
    if pd.isna(row['years_exp']) 
    else row['years_exp'],
    axis=1
)

In [29]:
df_model.groupby(['seniority', 'Job Category'])['years_exp'].agg(['mean', 'median', 'count'])

                              mean  median  count
seniority Job Category
junior    Data Analyst    3.000000     3.0      1
mid       AI Engineer     4.000000     3.5      8
          Data Analyst    3.093750     3.0     64
          Data Scientist  4.200704     4.0    284
          Deep Learning   2.000000     2.0      1
          ML engineer     5.411765     5.0     17
senior    AI Engineer     4.666667     4.0      3
          Data Analyst    4.818182     5.0     22
          Data Scientist  4.682540     5.0    126
          ML engineer     4.333333     4.0      6

In [30]:
df_model['years_exp'].value_counts()

years_exp
5.0     149
3.0     131
2.0     108
4.0      39
7.0      36
10.0     22
1.0      17
8.0      16
6.0       7
15.0      4
9.0       3
Name: count, dtype: int64

In [31]:
df_model.loc[df_model.index==697]

,Job Title,Company,Location,Salary Estimate,Job Description,Job Age,Unnamed: 0,Rating,Company Name,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Country,Hourly,Glassdoor_Estimate,Employer_Provided,currency,min_salary,max_salary,avg_salary,Skills,cleaned_Job,Writing skills,SAS,SAP,Relational databases,Data analytics,Project coordination,SDLC,Mandarin,Quantitative analysis,Forecasting,Public speaking,Systems design,Tooling,Organization design,Application development,SharePoint,SolidWorks,C++,Data management,Banking,TestNG,Tableau,Authentication,SVN,Public health,Web analytics,Cassandra,Yardi,IIS,JavaScript,Predictive analytics,Natural language processing,Web accessibility,Quality assurance,Virtualization,Time management,Research & development,Conflict management,Business analysis,Computer science,Embedded software,Debugging,CI/CD,Computer vision,Moving,E-commerce,Regression analysis,Microsoft Access,Oracle,CAD,Business processes,Data mining,System design,Data collection,Salesforce Marketing Cloud,Fiddler,Ansible,D3.js,Multilingual,Pro/ENGINEER,T-SQL,Waterfall,C#,Wireframing,Ontology,Military,XML,Software troubleshooting,SSRS,Market analysis,Epic,OOP,Marketing,CRM software,WAN,Project management,SASS,Risk management,Business requirements,PaaS,HP ALM,Recruiting,Performance tuning,Python,Web development,Program management,Microbiology,Customer retention,Statistical analysis,FedRAMP,Microservices,Release management,Database management,Solution architecture,Controlling experience,Vendor management,Django,Node.js,TypeScript,Elasticsearch,Linux,Distributed systems,Schematics,Databases,Mentoring,Jira,Scala,5G,Wealth management,Help desk,REST,SOX,Spark,Warehouse management system,Google Cloud Platform,Sales,Internet of things,Filing,Logistics,IT,Systems engineering,Microsoft PowerPoint,Financial analysis,.NET,Robotics,Signal processing,QlikView,Continuous improvement,Investment,Data centre experience,Big data,AWS,DevOps,Data structures,Software architecture,Cost management,Scripting,NetSuite,Requirements gathering,Requirements analysis,Data entry,Visual Basic,Load balancing,Microsoft Word,Test automation,MATLAB,Scalability,Financial modeling,Salesforce,Apache Hive,Redshift,Google Suite,Change management,SAP SuccessFactors,Operations management,Data visualization,FISMA,TCP,Confluence,SDKs,Russian,R,Data analysis skills,Deployment,Product development,Computer skills,Salt,Windows,Organisational skills,Management,Kanban,Analysis skills,UI,Performance management,Microsoft Powerpoint,Software testing,Process improvement,English,Figma,Pivot tables,Mechanical engineering,Trello,Medical imaging,Statistical software,IT service management,Hospitality,Cloud development,SaaS,System architecture,VoIP,GAMP,Machine learning,Presentation skills,Microsoft Office,Data warehouse,Disaster recovery,Front-end development,DoD experience,RBAC,ERP systems,System administration,Analytics,Maths,Azure,A/B testing,Japanese,Market research,Clinical development,Database development,Fraud prevention and detection,Bootstrap,TensorFlow,Test-driven development,Operating systems,New Relic,Usability,Math,Software development,Statistics,MongoDB,Contract management,.NET Core,Agile,Operations research,Content development,Marketing mix modeling,Terrafrom,Experimental design,Alteryx,Calculus,ServiceNow,Fanuc,Interviewing,Unity,Pricing,Computer networking,Customer service,Graph databases,FEA,French,DB2,GitHub,Bilingual,Mobile applications,SSO,Docker,Project management software,Data modelling,Microsoft SQL Server,Organizational skills,Clinical research,Supply chain,Taxonomy,HIPAA,Spanish,Cucumber (software testing tool),Telecommunication,Internet of Things,Visual Studio,Financial planning,Crystal Reports,Clinical laboratory experience,Data science,Quality control,EDI,NoSQL,Administrative experience,Biotechnology,Managed care,Team management,Construction,Unreal Engine,Test management tools,S3,Relationship management,Knowledge management,CSS,Root cause analysis,Laboratory information management systems,Metadata,Accounts payable,AutoCAD,Biostatistics,Research,Qualitative research,SCCM,Computer operation,Social listening,Electrical engineering,Kubernetes,Optics,Semantic Web,Barista experience,User acceptance testing,Software deployment,React,C,Financial services,Microsoft Windows Server,Algorithm design,PostgreSQL,Java,Cloud computing,Image processing,Data visualisation,Leadership,Project leadership,Enterprise software,Accounting software,Git,Proposal writing,Distributed control systems,Revit,Configuration management,Revenue cycle management,Sensors,Talent acquisition,Geometry,Adobe Photoshop,Deep learning,Information security,Program design,AI,Computer literacy,Go,APIs,iOS,SQL,SAFe,Quality inspection,Microsoft Outlook,Data modeling,Scientific research,Design patterns,Cloud infrastructure,Business intelligence,Selenium,Product demos,Rust (programming language),MRP,Incident management,FPGA,Microsoft Excel,Hadoop,Swift,Communication skills,Google Analytics,JSON,Terraform,Power BI,years_exp,seniority,Job Category,skill_num
697,Business Data Analyst,NaN,"New York, NY",$36K-$71K,(We are unable to sponsor for this role now or...,NaN,933.0,3.8,Fareportal\n3.8,"New York, NY",1001 to 5000 employees,2002.0,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com",USA,0,1,0,$,36.0,71.0,53.5,NaN,we are unable to sponsor for this role now or ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,2.0,mid,Data Analyst,13

## explain the previous models
- shortly : lasso is better than ridge with or without hyperparameter tunning
- MAE: model is off by $23k in training, and $25k in testing
- R2: explains 42% of the avg salary varience
- to explain more vereince, i will try to extract years of experience , but the problem is that not all the new data have years in job descreption as old jobs data,
to handle that i will determine the years based on seniotrity col, (see the mean  years for mid, for senior, for junior, and mid ,.. ) and also use job category since senior in ds hase different years of exp than ai engineer

## RandomForest Regressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor(n_estimators=100,random_state=42)
rf_pipeline=make_pipeline(preprocessor,rf)
rf_pipeline.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[['Categorical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['seniority', 'Job Category'], dtype='str')],
                                                 ['Numarical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strat...
                                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
       'SAS', 'SAP', 'Relational databases', 'Data analytics',
       'Project coordination', 'SDLC',
       ...
       'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
       'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
       'skill_num'],
      dtype='str', length=355)]],
                                   verbose_feature_names_out=False)),
                ('randomforestregressor',
                 RandomForestRegressor(random_state=42))])

In [34]:
evaluate_regression(reg=rf_pipeline,X_train=X_train,X_test=X_test,y_train=y_train,y_test=y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 5.544
- MSE = 72.734
- RMSE = 8.528
- R^2 = 0.949

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 14.965
- MSE = 544.432
- RMSE = 23.333
- R^2 = 0.635

- even better more than lasso 
- but still there is overfitting since r2 in training is 94%, but in test is 63%

In [ ]:
rf_pipeline.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[['Categorical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore',
                                                                   sparse_output=False))]),
                                    Index(['seniority', 'Job Category'], dtype='str')],
                                   ['Numarical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     Stan...ler())]),
                                    Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
          'SAS', 'SAP', 'Relational databases', 'Data analytics',
          'Project coordination', 'SDLC',
          ...
          'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
          'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
          'skill_num'],
         dtype='str', length=355)]],
                     verbose_feature_names_out=False)),
  ('randomforestregressor', RandomForestRegressor(random_state=42))],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[['Categorical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse_output=False))]),
                                  Index(['seniority', 'Job Category'], dtype='str')],
                                 ['Numarical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   Stan...ler())]),
                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
        'SAS', 'SAP', 'Relational databases', 'Data analytics',
        'Project coordination', 'SDLC',
        ...
        'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
        'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
        'skill_num'],
       dtype='str', length=355)]],
                   verbose_feature_names_out=False),
 'randomforestregressor': RandomForestRegressor(random_state=42),
 'columntransformer__force_int_remainder_cols': 'deprecated',
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [['Categorical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
   Index(['seniority', 'Job Category'], dtype='str')],
  ['Numarical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
          'SAS', 'SAP', 'Relational databases', 'Data analytics',
          'Project coordination', 'SDLC',
          ...
          'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
          'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
          'skill_num'],
         dtype='str', length=355)]],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': False,
 'columntransformer__Categorical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 'columntransformer__Numarical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__Categorical__memory': None,
 'columntransformer__Categorical__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='ignore', sparse_output=False))],
 'columntransformer__Categorical__transform_input': None,
 'columntransformer__Categorical__verbose': False,
 'columntransformer__Categorical__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__Categorical__onehotencoder': OneHotEncoder(handle_unknown='ignore', sparse_output=False),
 'columntransformer__Categorical__simpleimputer__add_indicator': False,
 'columntransformer__Categorical__simpleimputer__copy': True,
 'columntransformer__Categorical__simpleimputer__fill_value': None,
 'columntransformer__Categorical__simpleimputer__keep_empty_features': False,
 'columntransformer__Categorical__simpleimputer__missing_values': nan,
 'columntransformer__Categorical__simpleimputer__strategy': 'most_frequent',
 'columntransformer__Categorical__onehotencoder__categories': 'auto',
 'columntransformer__Categorical__onehotencoder__drop': None,
 'columntransformer__Categorical__onehotencoder__dtype': numpy.float64,
 'columntransformer__Categorical__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__Categorical__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__Categorical__onehotencoder__max_categories': None,
 'columntransformer__Categorical__onehotencoder__min_frequency': None,
 'columntransformer__Categorical__onehotencoder__sparse_output': False,
 'columntransformer__Numarical__memory': None,
 'columntransformer__Numarical__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__Numarical__transform_input': None,
 'columntransformer__Numarical__verbose': False,
 'columntransformer__Numarical__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__Numarical__standardscaler': StandardScaler(),
 'columntransformer__Numarical__simpleimputer__add_indicator': False,
 'columntransformer__Numarical__simpleimputer__copy': True,
 'columntransformer__Numarical__simpleimputer__fill_value': None,
 'columntransformer__Numarical__simpleimputer__keep_empty_features': False,
 'columntransformer__Numarical__simpleimputer__missing_values': nan,
 'columntransformer__Numarical__simpleimputer__strategy': 'median',
 'columntransformer__Numarical__standardscaler__copy': True,
 'columntransformer__Numarical__standardscaler__with_mean': True,
 'columntransformer__Numarical__standardscaler__with_std': True,
 'randomforestregressor__bootstrap': True,
 'randomforestregressor__ccp_alpha': 0.0,
 'randomforestregressor__criterion': 'squared_error',
 'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 1.0,
 'randomforestregressor__max_leaf_nodes': None,
 'randomforestregressor__max_samples': None,
 'randomforestregressor__min_impurity_decrease': 0.0,
 'randomforestregressor__min_samples_leaf': 1,
 'randomforestregressor__min_samples_split': 2,
 'randomforestregressor__min_weight_fraction_leaf': 0.0,
 'randomforestregressor__monotonic_cst': None,
 'randomforestregressor__n_estimators': 100,
 'randomforestregressor__n_jobs': None,
 'randomforestregressor__oob_score': False,
 'randomforestregressor__random_state': 42,
 'randomforestregressor__verbose': 0,
 'randomforestregressor__warm_start': False}

In [ ]:
rf_grid={
    "randomforestregressor__n_estimators":[100,300],
    "randomforestregressor__max_depth":[10,30],
    "randomforestregressor__min_samples_leaf":[1,2,3,4],
    "randomforestregressor__min_samples_split":[2,5,8]
}
rf_grid=GridSearchCV(estimator=rf_pipeline,
                     param_grid=rf_grid,
                     cv=5,
                     scoring="neg_mean_squared_error",
                     n_jobs=-1,
                     verbose=1
                     )
rf_grid.fit(X_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[['Categorical',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder(handle_unknown='ignore',
                                                                                                        sparse_output=False))]),
                                                                         Index(['seniority', 'Job Category'], dtype='str')],
                                                                        ['Numarical',
                                                                         Pipeline(steps=[('simple...
                                                          verbose_feature_names_out=False)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'randomforestregressor__max_depth': [10, 30],
                         'randomforestregressor__min_samples_leaf': [1, 2, 3,
                                                                     4],
                         'randomforestregressor__min_samples_split': [2, 5, 8],
                         'randomforestregressor__n_estimators': [100, 300]},
             scoring='neg_mean_squared_error', verbose=1)

In [41]:
evaluate_regression(reg=rf_grid,X_train=X_train,X_test=X_test,y_train=y_train,y_test=y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 5.473
- MSE = 68.988
- RMSE = 8.306
- R^2 = 0.952

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 14.679
- MSE = 514.934
- RMSE = 22.692
- R^2 = 0.655

- not that big deifference

In [47]:
rf_grid.best_params_

{'randomforestregressor__max_depth': 30,
 'randomforestregressor__min_samples_leaf': 1,
 'randomforestregressor__min_samples_split': 2,
 'randomforestregressor__n_estimators': 300}

## XGBOOST

In [ ]:
from xgboost import XGBRegressor

xgb=XGBRegressor(random_state=42,verbosity=0)
xgb_pipe=make_pipeline(preprocessor,xgb)
xgb_pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[['Categorical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['seniority', 'Job Category'], dtype='str')],
                                                 ['Numarical',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strat...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [49]:
evaluate_regression(reg=xgb_pipe,X_train=X_train,X_test=X_test,y_train=y_train,y_test=y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 1.290
- MSE = 4.167
- RMSE = 2.041
- R^2 = 0.997

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 11.120
- MSE = 413.654
- RMSE = 20.338
- R^2 = 0.723

- significent improvement, but still there is overfitting, since r2 in train 99%, in test 72%
- use tunning to reduce overfitting

In [51]:
xgb_pipe.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[['Categorical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='most_frequent')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore',
                                                                   sparse_output=False))]),
                                    Index(['seniority', 'Job Category'], dtype='str')],
                                   ['Numarical',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     Stan...ler())]),
                                    Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
          'SAS', 'SAP', 'Relational databases', 'Data analytics',
          'Project coordination', 'SDLC',
          ...
          'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
          'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
          'skill_num'],
         dtype='str', length=355)]],
                     verbose_feature_names_out=False)),
  ('xgbregressor',
   XGBRegressor(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bynode=None,
                colsample_bytree=None, device=None, early_stopping_rounds=None,
                enable_categorical=False, eval_metric=None, feature_types=None,
                feature_weights=None, gamma=None, grow_policy=None,
                importance_type=None, interaction_constraints=None,
                learning_rate=None, max_bin=None, max_cat_threshold=None,
                max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
                max_leaves=None, min_child_weight=None, missing=nan,
                monotone_constraints=None, multi_strategy=None, n_estimators=None,
                n_jobs=None, num_parallel_tree=None, ...))],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[['Categorical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='most_frequent')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse_output=False))]),
                                  Index(['seniority', 'Job Category'], dtype='str')],
                                 ['Numarical',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   Stan...ler())]),
                                  Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
        'SAS', 'SAP', 'Relational databases', 'Data analytics',
        'Project coordination', 'SDLC',
        ...
        'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
        'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
        'skill_num'],
       dtype='str', length=355)]],
                   verbose_feature_names_out=False),
 'xgbregressor': XGBRegressor(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...),
 'columntransformer__force_int_remainder_cols': 'deprecated',
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [['Categorical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
   Index(['seniority', 'Job Category'], dtype='str')],
  ['Numarical',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['Hourly', 'Glassdoor_Estimate', 'Employer_Provided', 'Writing skills',
          'SAS', 'SAP', 'Relational databases', 'Data analytics',
          'Project coordination', 'SDLC',
          ...
          'Microsoft Excel', 'Hadoop', 'Swift', 'Communication skills',
          'Google Analytics', 'JSON', 'Terraform', 'Power BI', 'years_exp',
          'skill_num'],
         dtype='str', length=355)]],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': False,
 'columntransformer__Categorical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 'columntransformer__Numarical': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__Categorical__memory': None,
 'columntransformer__Categorical__steps': [('simpleimputer',
   SimpleImputer(strategy='most_frequent')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='ignore', sparse_output=False))],
 'columntransformer__Categorical__transform_input': None,
 'columntransformer__Categorical__verbose': False,
 'columntransformer__Categorical__simpleimputer': SimpleImputer(strategy='most_frequent'),
 'columntransformer__Categorical__onehotencoder': OneHotEncoder(handle_unknown='ignore', sparse_output=False),
 'columntransformer__Categorical__simpleimputer__add_indicator': False,
 'columntransformer__Categorical__simpleimputer__copy': True,
 'columntransformer__Categorical__simpleimputer__fill_value': None,
 'columntransformer__Categorical__simpleimputer__keep_empty_features': False,
 'columntransformer__Categorical__simpleimputer__missing_values': nan,
 'columntransformer__Categorical__simpleimputer__strategy': 'most_frequent',
 'columntransformer__Categorical__onehotencoder__categories': 'auto',
 'columntransformer__Categorical__onehotencoder__drop': None,
 'columntransformer__Categorical__onehotencoder__dtype': numpy.float64,
 'columntransformer__Categorical__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__Categorical__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__Categorical__onehotencoder__max_categories': None,
 'columntransformer__Categorical__onehotencoder__min_frequency': None,
 'columntransformer__Categorical__onehotencoder__sparse_output': False,
 'columntransformer__Numarical__memory': None,
 'columntransformer__Numarical__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__Numarical__transform_input': None,
 'columntransformer__Numarical__verbose': False,
 'columntransformer__Numarical__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__Numarical__standardscaler': StandardScaler(),
 'columntransformer__Numarical__simpleimputer__add_indicator': False,
 'columntransformer__Numarical__simpleimputer__copy': True,
 'columntransformer__Numarical__simpleimputer__fill_value': None,
 'columntransformer__Numarical__simpleimputer__keep_empty_features': False,
 'columntransformer__Numarical__simpleimputer__missing_values': nan,
 'columntransformer__Numarical__simpleimputer__strategy': 'median',
 'columntransformer__Numarical__standardscaler__copy': True,
 'columntransformer__Numarical__standardscaler__with_mean': True,
 'columntransformer__Numarical__standardscaler__with_std': True,
 'xgbregressor__objective': 'reg:squarederror',
 'xgbregressor__base_score': None,
 'xgbregressor__booster': None,
 'xgbregressor__callbacks': None,
 'xgbregressor__colsample_bylevel': None,
 'xgbregressor__colsample_bynode': None,
 'xgbregressor__colsample_bytree': None,
 'xgbregressor__device': None,
 'xgbregressor__early_stopping_rounds': None,
 'xgbregressor__enable_categorical': False,
 'xgbregressor__eval_metric': None,
 'xgbregressor__feature_types': None,
 'xgbregressor__feature_weights': None,
 'xgbregressor__gamma': None,
 'xgbregressor__grow_policy': None,
 'xgbregressor__importance_type': None,
 'xgbregressor__interaction_constraints': None,
 'xgbregressor__learning_rate': None,
 'xgbregressor__max_bin': None,
 'xgbregressor__max_cat_threshold': None,
 'xgbregressor__max_cat_to_onehot': None,
 'xgbregressor__max_delta_step': None,
 'xgbregressor__max_depth': None,
 'xgbregressor__max_leaves': None,
 'xgbregressor__min_child_weight': None,
 'xgbregressor__missing': nan,
 'xgbregressor__monotone_constraints': None,
 'xgbregressor__multi_strategy': None,
 'xgbregressor__n_estimators': None,
 'xgbregressor__n_jobs': None,
 'xgbregressor__num_parallel_tree': None,
 'xgbregressor__random_state': 42,
 'xgbregressor__reg_alpha': None,
 'xgbregressor__reg_lambda': None,
 'xgbregressor__sampling_method': None,
 'xgbregressor__scale_pos_weight': None,
 'xgbregressor__subsample': None,
 'xgbregressor__tree_method': None,
 'xgbregressor__validate_parameters': None,
 'xgbregressor__verbosity': 0}

In [56]:
xgb_param_grid = {
    'xgbregressor__n_estimators': [100, 300],
    'xgbregressor__max_depth': [3, 5],
    'xgbregressor__learning_rate': [0.05, 0.1],
    'xgbregressor__subsample': [0.7, 1.0],
    'xgbregressor__colsample_bytree': [0.7, 1.0],
    'xgbregressor__reg_alpha': [0, 1],
    'xgbregressor__reg_lambda': [1, 10]
}
xgb_grid = GridSearchCV(
    estimator=xgb_pipe,
    param_grid=xgb_param_grid,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    verbose=1
)
xgb_grid.fit(X_train, y_train)

evaluate_regression(xgb_grid, X_train, y_train, X_test, y_test)

Fitting 5 folds for each of 128 candidates, totalling 640 fits
------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 2.601
- MSE = 14.396
- RMSE = 3.794
- R^2 = 0.990

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 12.107
- MSE = 422.420
- RMSE = 20.553
- R^2 = 0.717

the default better & faster

## CONT'd